### ISSUE TITLE
Error in Denizen Script after updating to the newest build (1572)

### ISSUE THREAD

**Issue by Newwings** [DenizenScript/Denizen-For-Bukkit#1002]
Hello, in older Versions worked this skript:
```javascript
Feuerwehr:
  Type: world
  events:
     on dshafguahsdifu8sz7ds8uf98dfsfeuerwehr_fraktion_Einsatz_Annehmen command:
        - if <player.has_permission[potato.Feuerwehr]>
            {
                if <server.flag[Fraktion_Feuerwehr_Einsatz]> == 1
                {
                 - compass 239,63,-55,PotatoMC
                 - narrate "<gold><italic>Tipp<&co> <gray><italic>Dein Kompass zeigt dir den Weg. (Schutthaufen NewOrdos)"
                 - permission add potato.feuerwehr.einsatz.1
                }
                else if <server.flag[Fraktion_Feuerwehr_Einsatz]> == 2
                {
                 - compass 796,68,-2298,PotatoMC
                 - narrate "<gold><italic>Tipp<&co> <gray><italic>Dein Kompass zeigt dir den Weg. (Baumsturz Montiago)"
                 - permission add potato.feuerwehr.einsatz.2
                }
                else narrate "<red>Es gibt zurzeit keinen Einsatz."
            }
        - determine FULFILLED
```
in the newest build this script will throw out an error:
```
[16:02:51] [Server thread/INFO]: Newwings issued server command: /dshafguahsdifu8sz7ds8uf98dfsfeuerwehr_fraktion_Einsatz_Annehmen
[16:02:51] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mEvent[0;30;1m': [0;30;1mType='[0;33;1mon 
                   DSHAFGUAHSDIFU8SZ7DS8UF98DFSFEUERWEHR_FRAKTION_EINSATZ_ANNEHMEN 
                   command[0;30;1m'  [0;30;1mContainer='[0;36;1mFEUERWEHR[0;33;1m(WORLD)[0;30;1m'  
                   player=p@Newwings[0;30;1mContext='[0;33;1m{cuboids=li@, args=li@, 
                   raw_args=, 
                   command=DSHAFGUAHSDIFU8SZ7DS8UF98DFSFEUERWEHR_FRAKTION_EINSATZ_ANNEHMEN, 
                   server=false, parsed_args=li@}[0;30;1m' [m
[16:02:51] [Server thread/INFO]: [0;35;1m+- Building event 'ON 
                   DSHAFGUAHSDIFU8SZ7DS8UF98DFSFEUERWEHR_FRAKTION_EINSATZ_ANNEHMEN 
                   COMMAND' for FEUERWEHR ---------+ [m
[16:02:51] [Server thread/INFO]: [0;35;1m [0;37;1mStarting InstantQueue 
                   'FEUERWEHR_SoundElevenInitiatives'... [m
[16:02:51] [Server thread/INFO]: [0;35;1m [0;37;1mQueue 'FEUERWEHR_SoundElevenInitiatives' Executing: IF 
                   "<player.has_permission[potato.Feuerwehr]>" "{" "if" 
                   "<server.flag[Fraktion_Feuerwehr_Einsatz]>" "==" "1" "{" 
                   "-" "compass" "239,63,-55,PotatoMC" "-" "narrate" 
                   "<gold><italic>Tipp<&co> <gray><italic>Dein Kompass zeigt 
                   dir den Weg. (Schutthaufen NewOrdos)" "-" "permission" 
                   "add" "potato.feuerwehr.einsatz.1" "}" "else" "if" 
                   "<server.flag[Fraktion_Feuerwehr_Einsatz]>" "==" "2" "{" 
                   "-" "compass" "796,68,-2298,PotatoMC" "-" "narrate" 
                   "<gold><italic>Tipp<&co... * snip! * [m
[16:02:51] [Server thread/INFO]: [0;35;1m+- Executing dCommand: IF/p@Newwings ---------+ [m
[16:02:51] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mIF[0;30;1m': [0;30;1muse_braces='[0;33;1mtrue[0;30;1m' [m
[16:02:51] [Server thread/INFO]: [0;35;1m [0;37;1mFilled tag <player.has_permission[potato.Feuerwehr]> with 
                   'true'. [m
[16:02:51] [Server thread/INFO]: [0;35;1m [0;31;1mERROR in script 'FEUERWEHR'! [0;37;1mWoah!! An exception has been 
                   called with this command! [m
[16:02:51] [Server thread/INFO]: [0;35;1m [0;31;1mERROR in script 'FEUERWEHR'! [0;37;1mInternal exception was 
                   thrown! [m
[16:02:51] [Server thread/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[16:02:51] [Server thread/WARN]: 	at java.util.ArrayList.rangeCheck(Unknown Source)
[16:02:51] [Server thread/WARN]: 	at java.util.ArrayList.get(Unknown Source)
[16:02:51] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.commands.core.IfCommand.execute(IfCommand.java:101)
[16:02:51] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:235)
[16:02:51] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:51)
[16:02:51] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:660)
[16:02:51] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:53)
[16:02:51] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:519)
[16:02:51] [Server thread/WARN]: 	at net.aufdemrand.denizencore.events.OldEventManager.doEvents(OldEventManager.java:233)
[16:02:51] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.containers.core.BukkitWorldScriptHelper.doEvents(BukkitWorldScriptHelper.java:63)
[16:02:51] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.containers.core.BukkitWorldScriptHelper.doEvents(BukkitWorldScriptHelper.java:54)
[16:02:51] [Server thread/WARN]: 	at net.aufdemrand.denizen.events.core.CommandSmartEvent.playerCommandPreprocess(CommandSmartEvent.java:215)
[16:02:51] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:02:51] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:02:51] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:02:51] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:02:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[16:02:51] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:02:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:02:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:02:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1125)
[16:02:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
[16:02:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:02:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:02:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[16:02:51] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:02:51] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[16:02:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[16:02:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[16:02:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[16:02:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[16:02:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[16:02:51] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:02:51] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1m(Attempted: IF 
                   "<player.has_permission[potato.Feuerwehr]>" "{" "if" 
                   "<server.flag[Fraktion_Feuerwehr_Einsatz]>" "==" "1" "{" 
                   "-" "compass" "239,63,-55,PotatoMC" "-" "narrate" 
                   "<gold><italic>Tipp<&co> <gray><italic>Dein Kompass zeigt 
                   dir den Weg. (Schutthaufen NewOrdos)" "-" "permission" 
                   "add" "potato.feuerwehr.einsatz.1" "}" "else" "if" 
                   "<server.flag[Fraktion_Feuerwehr_Einsatz]>" "==" "2" "{" 
                   "-" "compass" "796,68,-2298,PotatoMC" "-" "narrate" 
                   "<gold><italic>Tipp<&co> <gray><italic>Dein Kompass zeigt 
                   dir d... * snip! * [m
[16:02:51] [Server thread/INFO]: [0;35;1m+---------------------+ [m
[16:02:51] [Server thread/INFO]: [0;35;1m [0;37;1mQueue 'FEUERWEHR_SoundElevenInitiatives' Executing: 
                   DETERMINE "FULFILLED" [m
[16:02:51] [Server thread/INFO]: [0;35;1m+- Executing dCommand: DETERMINE/p@Newwings ---------+ [m
[16:02:51] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mDETERMINE[0;30;1m': outcome='[0;36;1mFULFILLED[0;30;1m'  
                   passively='[0;36;1mfalse[0;30;1m' [m
[16:02:51] [Server thread/INFO]: [0;35;1m [0;37;1mCompleting queue 'FEUERWEHR_SoundElevenInitiatives' in 
                   5ms. [m
```
I don't know what is wrong there...

**Comment by mcmonkey4eva** [comment]
No, that script never worked, you're missing a `-` on one of the `if`s

**Comment by Newwings** [comment]
Ok thanks. :) This is mysterious...
