### ISSUE TITLE
Could not pass event PrepareItemCraftEvent to Denizen v0.9.6-SNAPSHOT (build 1575)

### ISSUE THREAD

**Issue by Elvi81** [DenizenScript/Denizen-For-Bukkit#1043]
Any idea why this is suddenly happening?
```
[19:18:30] [Server thread/ERROR]: Could not pass event PrepareItemCraftEvent to Denizen v0.9.6-SNAPSHOT (build 1575)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:730) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.CraftingManager.craft(CraftingManager.java:298) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntitySheep.a(EntitySheep.java:225) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntitySheep.b(EntitySheep.java:194) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntitySheep.createChild(EntitySheep.java:242) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PathfinderGoalBreed.g(PathfinderGoalBreed.java:70) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PathfinderGoalBreed.e(PathfinderGoalBreed.java:45) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PathfinderGoalSelector.a(PathfinderGoalSelector.java:91) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityInsentient.doTick(EntityInsentient.java:474) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityLiving.m(EntityLiving.java:1625) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityInsentient.m(EntityInsentient.java:339) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityAgeable.m(EntityAgeable.java:139) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityAnimal.m(EntityAnimal.java:23) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntitySheep.m(EntitySheep.java:63) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityLiving.t_(EntityLiving.java:1486) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.EntityInsentient.t_(EntityInsentient.java:194) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.World.entityJoinedWorld(World.java:1607) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.World.g(World.java:1582) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.World.tickEntities(World.java:1425) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:783) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_8_R2.InventoryCrafting.getOwner(InventoryCrafting.java:46) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.inventory.CraftInventory.getHolder(CraftInventory.java:458) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.aufdemrand.denizen.objects.dInventory.loadIdentifiers(dInventory.java:459) ~[?:?]
	at net.aufdemrand.denizen.objects.dInventory.<init>(dInventory.java:272) ~[?:?]
	at net.aufdemrand.denizen.scripts.containers.core.BukkitWorldScriptHelper.craftItemEvent(BukkitWorldScriptHelper.java:2363) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor464.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	... 28 more
```
*__Edit by Morphan1:__ Put log in a scrollable block*

**Comment by Morphan1** [comment]
It looks like an old issue was revived by Spigot somehow... Or maybe it never went away and you found it again. What type of inventory is it that's being opened?

**Comment by Elvi81** [comment]
Your guess is as good as mine, this just poped up out of the blue and i've never seen it before.

**Comment by Elvi81** [comment]
It seems the top part of the error shows up more often than the later part where it starts with Caused by: java.lang.NullPointerException.

**Comment by Morphan1** [comment]
...that part looks like a sheep is trying to open up an inventory o.O what is happening

**Comment by mcmonkey4eva** [comment]
Specifically, a sheep is breeding, and that breeding process involves crafting an item for some reason.

**Comment by Morphan1** [comment]
This has got to be a Spigot issue.

**Comment by mcmonkey4eva** [comment]
That or he's running some strange mod

**Comment by Elvi81** [comment]
No mods on this server, just plugins so it's more or less vanilla

**Comment by mcmonkey4eva** [comment]
@Morphan1 wanna send this Spigot's way?

**Comment by Morphan1** [comment]
@Elvi81 what's the output of /version

**Comment by Elvi81** [comment]
This server is running CraftBukkit version git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

**Comment by Morphan1** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-887

**Comment by Elvi81** [comment]
Apparently it's supposed to be fixed now according to that spigot post, hard to tell if that's the trueth tho as of yet.

**Comment by Morphan1** [comment]
Well it's definitely fixed internally
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/3408adb

**Comment by Elvi81** [comment]
question is what version it's in, 1.8.3 only goes up to build 422 and i can't use 1.8.4 or .5 yet

**Comment by Morphan1** [comment]
It's in 1.8.4
