### ISSUE TITLE
issue with denizen #1576 could not create npc spawn event 1.8.6 spigot

### ISSUE THREAD

**Issue by GeForcez** [DenizenScript/Denizen-For-Bukkit#1050]
hey just want to adress this error
> 
```
[20:46:47 INFO]: Done (5,313s)! For help, type "help" or "?"
[20:46:47 INFO]: GroupManager - INFO - Bukkit Permissions Updated!
[20:46:48 ERROR]: Could not pass event NPCSpawnEvent to Denizen v0.9.6-SNAPSHOT (build 1576)
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c5146ba-01
930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:191) [citizens.jar:?]
        at net.citizensnpcs.EventListen.spawn(EventListen.java:428) [citizens.jar:?]
        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:405) [citizens.jar:?]
        at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:110) [citizens.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-c5146ba-0
1930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-c5146ba-019
30e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:59) [spigot.jar:git-Sp
igot-c5146ba-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [spigot.jar:git-Spi
got-c5146ba-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [spigot.jar
:git-Spigot-c5146ba-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [spigot.
jar:git-Spigot-c5146ba-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) [spigot.jar:git
-Spigot-c5146ba-01930e2]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) [spigot.jar:git-Spi
got-c5146ba-01930e2]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) [spigot.jar:git-Spig
ot-c5146ba-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:125) [spigot.jar:git-Spigot-c5146ba-0193
0e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:89) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:567) [spigot.jar:git-Spigot-c5146ba-0193
0e2]
        at org.bukkit.Location.getBlock(Location.java:87) [spigot.jar:git-Spigot-c5146ba-01930e2]
        at net.citizensnpcs.npc.MobEntityController.createEntity(MobEntityController.java:32) [citizens.jar:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:36) [citizens.jar:?]
        at net.citizensnpcs.npc.entity.HorseController.spawn(HorseController.java:38) [citizens.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:176) [citizens.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:125) [citizens.jar:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [citizens.jar:?]
        at net.citizensnpcs.Citizens$2.run(Citizens.java:295) [citizens.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-c5146ba-0193
0e2]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.
jar:git-Spigot-c5146ba-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-c5146ba-019
30e2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected 36 or less
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.setContents(CraftInventory.java:64) ~[spigot.jar:git-
Spigot-c5146ba-01930e2]
        at net.aufdemrand.denizen.npc.dNPCRegistry._registerNPC(dNPCRegistry.java:78) ~[?:?]
        at net.aufdemrand.denizen.objects.dNPC.<init>(dNPC.java:135) ~[?:?]
        at net.aufdemrand.denizen.npc.dNPCRegistry._registerNPC(dNPCRegistry.java:86) ~[?:?]
        at net.aufdemrand.denizen.npc.dNPCRegistry.onSpawn(dNPCRegistry.java:169) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c5146ba-
01930e2]
        ... 40 more
[20:46:48 ERROR]: Could not pass event NPCSpawnEvent to Denizen v0.9.6-SNAPSHOT (build 1576)
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c5146ba-01
930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:191) [citizens.jar:?]
        at net.citizensnpcs.EventListen.spawn(EventListen.java:428) [citizens.jar:?]
        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:405) [citizens.jar:?]
        at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:110) [citizens.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-c5146ba-0
1930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-c5146ba-019
30e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:59) [spigot.jar:git-Sp
igot-c5146ba-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [spigot.jar:git-Spi
got-c5146ba-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [spigot.jar
:git-Spigot-c5146ba-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [spigot.
jar:git-Spigot-c5146ba-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) [spigot.jar:git
-Spigot-c5146ba-01930e2]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) [spigot.jar:git-Spi
got-c5146ba-01930e2]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) [spigot.jar:git-Spig
ot-c5146ba-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:125) [spigot.jar:git-Spigot-c5146ba-0193
0e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:89) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:567) [spigot.jar:git-Spigot-c5146ba-0193
0e2]
        at org.bukkit.Location.getBlock(Location.java:87) [spigot.jar:git-Spigot-c5146ba-01930e2]
        at net.citizensnpcs.npc.MobEntityController.createEntity(MobEntityController.java:32) [citizens.jar:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:36) [citizens.jar:?]
        at net.citizensnpcs.npc.entity.HorseController.spawn(HorseController.java:38) [citizens.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:176) [citizens.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:125) [citizens.jar:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [citizens.jar:?]
        at net.citizensnpcs.Citizens$2.run(Citizens.java:295) [citizens.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-c5146ba-0193
0e2]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.
jar:git-Spigot-c5146ba-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-c5146ba-019
30e2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected 36 or less
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.setContents(CraftInventory.java:64) ~[spigot.jar:git-
Spigot-c5146ba-01930e2]
        at net.aufdemrand.denizen.npc.dNPCRegistry._registerNPC(dNPCRegistry.java:78) ~[?:?]
        at net.aufdemrand.denizen.objects.dNPC.<init>(dNPC.java:135) ~[?:?]
        at net.aufdemrand.denizen.npc.dNPCRegistry._registerNPC(dNPCRegistry.java:86) ~[?:?]
        at net.aufdemrand.denizen.npc.dNPCRegistry.onSpawn(dNPCRegistry.java:169) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c5146ba-
01930e2]
        ... 40 more
[20:46:48 ERROR]: Could not pass event NPCSpawnEvent to Denizen v0.9.6-SNAPSHOT (build 1576)
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c5146ba-01
930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:191) [citizens.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:125) [citizens.jar:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [citizens.jar:?]
        at net.citizensnpcs.Citizens$2.run(Citizens.java:295) [citizens.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-c5146ba-0193
0e2]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.
jar:git-Spigot-c5146ba-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-c5146ba-019
30e2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected 36 or less
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.setContents(CraftInventory.java:64) ~[spigot.jar:git-
Spigot-c5146ba-01930e2]
        at net.aufdemrand.denizen.npc.dNPCRegistry._registerNPC(dNPCRegistry.java:78) ~[?:?]
        at net.aufdemrand.denizen.objects.dNPC.<init>(dNPC.java:135) ~[?:?]
        at net.aufdemrand.denizen.npc.dNPCRegistry._registerNPC(dNPCRegistry.java:86) ~[?:?]
        at net.aufdemrand.denizen.npc.dNPCRegistry.onSpawn(dNPCRegistry.java:169) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c5146ba-
01930e2]
        ... 14 more
[20:46:48 ERROR]: Could not pass event NPCSpawnEvent to Denizen v0.9.6-SNAPSHOT (build 1576)
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c5146ba-01
930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:191) [citizens.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:125) [citizens.jar:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [citizens.jar:?]
        at net.citizensnpcs.Citizens$2.run(Citizens.java:295) [citizens.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-c5146ba-0193
0e2]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.
jar:git-Spigot-c5146ba-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-c5146ba-019
30e2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected 36 or less
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.setContents(CraftInventory.java:64) ~[spigot.jar:git-
Spigot-c5146ba-01930e2]
        at net.aufdemrand.denizen.npc.dNPCRegistry._registerNPC(dNPCRegistry.java:78) ~[?:?]
        at net.aufdemrand.denizen.objects.dNPC.<init>(dNPC.java:135) ~[?:?]
        at net.aufdemrand.denizen.npc.dNPCRegistry._registerNPC(dNPCRegistry.java:86) ~[?:?]
        at net.aufdemrand.denizen.npc.dNPCRegistry.onSpawn(dNPCRegistry.java:169) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c5146ba-
01930e2]
        ... 14 more
[20:46:48 ERROR]: Could not pass event NPCSpawnEvent to Denizen v0.9.6-SNAPSHOT (build 1576)
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c5146ba-01
930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c5146ba-
01930e2]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:191) [citizens.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:125) [citizens.jar:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [citizens.jar:?]
        at net.citizensnpcs.Citizens$2.run(Citizens.java:295) [citizens.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-c5146ba-0193
0e2]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.
jar:git-Spigot-c5146ba-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-c5146ba-01930
e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-c5146ba-019
30e2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected 36 or less
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.setContents(CraftInventory.java:64) ~[spigot.jar:git-
Spigot-c5146ba-01930e2]
        at net.aufdemrand.denizen.npc.dNPCRegistry._registerNPC(dNPCRegistry.java:78) ~[?:?]
        at net.aufdemrand.denizen.objects.dNPC.<init>(dNPC.java:135) ~[?:?]
        at net.aufdemrand.denizen.npc.dNPCRegistry._registerNPC(dNPCRegistry.java:86) ~[?:?]
        at net.aufdemrand.denizen.npc.dNPCRegistry.onSpawn(dNPCRegistry.java:169) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c5146ba-
01930e2]
        ... 14 more
```

**Comment by Talamar1** [comment]
What is the build version for your Citizen and spigot, because that doesn't look like 1.8.6

**Comment by Morphan1** [comment]
@Talamar1 it is 1.8.6
@mcmonkey4eva what.. did you change?

**Comment by GeForcez** [comment]
well let me see denizen is #1576 en citizens #1235

**Comment by mcmonkey4eva** [comment]
@GeForcez for some reason spoilers are highly restricted  here, can only make 'em under super duper specific circumstances :(

Anyway, try the latest dev release of Denizen :http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by mcmonkey4eva** [comment]
@Morphan1 I made inventories in C2 size:72 now. That way we can handle things like storage minecarts non-terribly. To compensate for that in Denizen, I had to add a line of code that tells it to... not take any size inventory other than the expected one: https://github.com/mcmonkey4eva/Denizen/commit/d66f8a5d2d882ca449c179cab8e4dc96806f6174 first change listed.

**Comment by GeForcez** [comment]
@Morphan1  ill try it out right away give me a sec
