### ISSUE TITLE
Crash with spigot 1.8.5 and denizen 0.9.6

### ISSUE THREAD

**Issue by Culvanen** [DenizenScript/Denizen-For-Bukkit#1052]
Hi, i have error in spigot 1.8.5 with denizen 0.9.6 (#1577)

Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Exception ticking world entities
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:800) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
	at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.java:122) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.isNPC(CitizensNPCRegistry.java:128) ~[?:?]
	at net.aufdemrand.denizen.objects.dEntity.isCitizensNPC(dEntity.java:71) ~[?:?]
	at net.aufdemrand.denizen.objects.dEntity.<init>(dEntity.java:305) ~[?:?]
	at net.aufdemrand.denizen.utilities.world.DenizenWorldAccess.b(DenizenWorldAccess.java:46) ~[?:?]
	at net.minecraft.server.v1_8_R3.World.b(World.java:1074) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.WorldServer.b(WorldServer.java:987) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1394) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	... 4 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.java:122) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.isNPC(CitizensNPCRegistry.java:128) ~[?:?]
	at net.aufdemrand.denizen.objects.dEntity.isCitizensNPC(dEntity.java:71) ~[?:?]
	at net.aufdemrand.denizen.objects.dEntity.<init>(dEntity.java:305) ~[?:?]
	at net.aufdemrand.denizen.utilities.world.DenizenWorldAccess.b(DenizenWorldAccess.java:46) ~[?:?]
	at net.minecraft.server.v1_8_R3.World.b(World.java:1074) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.WorldServer.b(WorldServer.java:987) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1394) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	... 4 more
[10:04:10] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
	at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.java:122) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.isNPC(CitizensNPCRegistry.java:128) ~[?:?]
	at net.aufdemrand.denizen.objects.dEntity.isCitizensNPC(dEntity.java:71) ~[?:?]
	at net.aufdemrand.denizen.objects.dEntity.<init>(dEntity.java:305) ~[?:?]
	at net.aufdemrand.denizen.utilities.world.DenizenWorldAccess.b(DenizenWorldAccess.java:46) ~[?:?]
	at net.minecraft.server.v1_8_R3.World.b(World.java:1074) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.WorldServer.b(WorldServer.java:987) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1394) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.5.jar:git-Spigot-17fce80-529e4cd]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 14 more
[10:04:10] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Vincent\Desktop\Serveur 1.8.3\.\crash-reports\crash-2015-06-03_10.04.10-server.txt
[10:04:10] [Server thread/INFO]: Stopping server

**Comment by GomaTerzu** [comment]
#1577 is Minecraft 1.8.6 already so use spigot 1.8.6 i guess

**Comment by mcmonkey4eva** [comment]
Update Citizens while you're updating things too.

**Comment by Culvanen** [comment]
Thanks for you reply problem solved with last warn:

[10:38:39] [Server thread/WARN]: [Citizens] Task #62 for Citizens v2.0.16-SNAPSHOT (build 1237) generated an exception
java.lang.NullPointerException
	at net.citizensnpcs.npc.entity.HumanController$1.run(HumanController.java:113) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
	at java.lang.Thread.run(Unknown Source)

**Comment by mcmonkey4eva** [comment]
How did you even create an error like that?
https://github.com/CitizensDev/Citizens2/blob/master/src/main/java/net/citizensnpcs/npc/entity/HumanController.java#L113 shouldn't error much...
Perhaps you deleted an NPC while it was still loading or something? 0.o

**Comment by Culvanen** [comment]
That error appear in start of server

**Comment by mcmonkey4eva** [comment]
Well... Citizens error, so report it there :)
