### ISSUE TITLE
Spigot 1.8.7-denizen snapshot 1597 - citizens2 1251 error 

### ISSUE THREAD

**Issue by cricketcricketcricket** [DenizenScript/Denizen-For-Bukkit#1143]
[21:08:17] [Server thread/WARN]: [Denizen] Task #90 for Denizen v0.9.7-SNAPSHOT (build 1597) generated an exception
java.lang.NoClassDefFoundError: org/bukkit/event/entity/ItemMergeEvent
	at net.aufdemrand.denizen.events.entity.ItemMergesScriptEvent.destroy(ItemMergesScriptEvent.java:88) ~[?:?]
	at net.aufdemrand.denizencore.events.ScriptEvent.reload(ScriptEvent.java:84) ~[?:?]
	at net.aufdemrand.denizencore.DenizenCore.loadScripts(DenizenCore.java:100) ~[?:?]
	at net.aufdemrand.denizen.Denizen$1.run(Denizen.java:825) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.entity.ItemMergeEvent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
	... 11 more
[21:08:17] [Server thread/INFO]: [Citizens] Loaded 0 NPCs.

**Comment by mcmonkey4eva** [comment]
Update Spigot to latest 1.8.7 or 1.8.8.

**Comment by cricketcricketcricket** [comment]
Hi, I am on 1.8.7. I will update to 1.8.8. Thank you - Larry

**Comment by Fortifier42** [comment]
Please close this if it is fixed :smile:

**Comment by mcmonkey4eva** [comment]
Assuming fixed. Please reply below if you would like this reopened.
