### ISSUE TITLE
/citizens reload leads to Denizen error and deleted NPCs

### ISSUE THREAD

**Issue by PsychoLynx** [DenizenScript/Denizen-For-Bukkit#1148]
Using the latest Spigot 1.8.8, denizen b#1497 and Citizens #b1256 This is on a fresh server with no NPCs or scripts before I created the NPC "Toivo". After performing the comment "Toivo" disappeared.

```
[11:32:34] [Server thread/INFO]: PsychoLynx issued server command: /npc create Toivo
[11:32:46] [Server thread/INFO]: PsychoLynx issued server command: /citizens reload
[11:32:46] [Server thread/INFO]: [0;35;1m [0;31;1mERROR! [0;37;1mInternal exception was thrown! [m
[11:32:46] [Server thread/WARN]: java.lang.RuntimeException: StackTraceOutput
[11:32:46] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.dNPC.getCitizen(dNPC.java:146)
[11:32:46] [Server thread/WARN]: 	at net.aufdemrand.denizen.npc.dNPCRegistry.getSpawnedNPCs(dNPCRegistry.java:134)
[11:32:46] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.triggers.core.ProximityTrigger$1.run(ProximityTrigger.java:165)
[11:32:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[11:32:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[11:32:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
[11:32:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[11:32:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[11:32:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[11:32:46] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[11:32:46] [Server thread/INFO]: [0;33;1m+> [dNPC] [0;37;1mUh oh! Denizen has encountered a NPE while trying to 
                   fetch an NPC. Has this NPC been removed? [m
[11:32:46] [Server thread/INFO]: [0;33;1m+> [dNPCRegistry] [0;37;1m[0;31;1mRemoved NPC from dRegistry. [m
```

**Comment by Morphan1** [comment]
I updated the format to make it easier to read. 

And uh... @mcmonkey4eva this looks like it's coming from your code?

**Comment by Fortifier42** [comment]
I believe this is because you haven't saved the npc yet? citizens doesn't automatically save when you reload, i.e. it is removed as it isn't in the citizens config files.

**Comment by Morphan1** [comment]
Oh hey, that sounds logical. 
Yeah, remember that any npcs made before saving will not show up after a reload, because they're not on the disk, and they can't be reloaded from a disk they're not on.

**Comment by mcmonkey4eva** [comment]
Yeah the Denizen error is literally just saying "oh shi- an NPC disappeared without visible reason!"
The deletion is a Citizens level problem as described above.

**Comment by mcmonkey4eva** [comment]
This should probably actually be sent in to the C2 issue tracker, as I'm not sure that's intended behavior.

**Comment by Fortifier42** [comment]
This can probably be closed yo
