### ISSUE TITLE
unable to take items from an inventory using commands

### ISSUE THREAD

**Issue by zozer** [DenizenScript/Denizen-For-Bukkit#1152]
i have an inventory script and i want to take an item in it and replace it with another. No matter what i try the inventory does not take out the item at all and then throws an error when trying to put a new item in. can this be fixed?

**Comment by mcmonkey4eva** [comment]
Sample script?
Error messages?

**Comment by zozer** [comment]
```
    on player clicks in inventory:
    - if <c.inventory.is[!=].to[in@combo_lock]> {
      - queue clear
      }
    - determine passively CANCELLED
    - if <c.item.is[==].to[<c.inventory.slot[1]>]> {
      - inventory close d:<c.inventory>
      - if <player.flag[unlock_dcl].as_list.is[==].to[<yaml[dcl].read[keys.<player.flag[loc_dcl]>]>]> {
        - narrate '<green>unlocked, you can use this button for 1 minute'
        - flag player pass_dcl:<player.flag[loc_dcl]> duration:1m
        }
        else {
        - narrate '<red>incorrect password'
        }
      - flag player loc_dcl:!
      }
      else {
      - flag <player> unlock_dcl:->:<c.item.display>
      - determine passively CANCELLED:false
      - wait 1t
      - inventory set o:i@air d:<c.inventory> slot:1
      - wait 1t
      - give i@wool to:<player.open_inventory>
      }
  loadYAML:
    - if !<yaml.list.contains[locks]> {
      - if !<server.has_file[dcomlocks/dcomlocks.yml]> {
        - yaml create 'id:dcl'
        - yaml 'savefile:dcomlocks/dcomlocks.yml' 'id:dcl'
        }
        else {
        - yaml 'load:dcomlocks/dcomlocks.yml' 'id:dcl'
        }
      }
combo_lock:
  type: inventory
  inventory: WORKBENCH 
  slots:
    - "[i@stone_button[display_name=enter:]]"
    - "[i@stone_button[display_name=1]] [i@stone_button[display_name=2]] [i@stone_button[display_name=3]]"
    - "[i@stone_button[display_name=4]] [i@stone_button[display_name=5]] [i@stone_button[display_name=6]]"
    - "[i@stone_button[display_name=7]] [i@stone_button[display_name=8]] [i@stone_button[display_name=9]]" 
```
is the script

**Comment by Fortifier42** [comment]
We will also need the error to determine what/where it went wrong :)

**Comment by zozer** [comment]
```
[21:54:37] [Server thread/INFO]: [0;35;1m+- Executing dCommand: GIVE/p@zozer_firehood ---------+ [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mFilled tag <player.open_inventory> with 
                   'in@generic[holder=WORKBENCH;contents=li@i@stone_button[display_name=enter&co]|i@stone_button[display_name=1]|i@stone_button[display_name=2]|i@stone_button[display_name=3]|i@stone_button[display_name=4]|i@stone_button[display_name=5]|i@stone_button[display_name=6]|i@stone_button[display_name=7]|i@stone_button[display_name=8]|i@stone_button[display_name=9];title=Crafting]'. [m
[21:54:37] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mGIVE[0;30;1m': [0;30;1mType='[0;33;1mITEM[0;30;1m'  
                   [0;30;1minventory='[0;33;1min@generic[holder=WORKBENCH;contents=li@i@stone_button[display_name=enter&co]|i@stone_button[display_name=1]|i@stone_button[display_name=2]|i@stone_button[display_name=3]|i@stone_button[display_name=4]|i@stone_button[display_name=5]|i@stone_button[display_name=6]|i@stone_button[display_name=7]|i@stone_button[display_name=8]|i@stone_button[display_name=9];title=Crafting][0;30;1m' 
                    [0;30;1mQuantity='[0;33;1m1.0[0;30;1m'  engrave='[0;36;1mfalse[0;30;1m'  unlimit_stack_size='[0;36;1mfalse[0;30;1m'  
                   [0;30;1mItems='<Y... * snip! * [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mThe inventory didn't have enough space, the rest of the items 
                   have been placed on the floor. [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;31;1mERROR in script 'COMBO_LOCK_HANDLER'! [0;37;1mWoah!! An exception has 
                   been called with this command! [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;31;1mERROR in script 'COMBO_LOCK_HANDLER'! [0;37;1mInternal exception was 
                   thrown! [m
[21:54:37] [Server thread/WARN]: java.lang.NullPointerException
[21:54:37] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.commands.item.GiveCommand.execute(GiveCommand.java:152)
[21:54:37] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:236)
[21:54:37] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:52)
[21:54:37] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:655)
[21:54:37] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue.access$000(TimedQueue.java:12)
[21:54:37] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue$1.run(TimedQueue.java:151)
[21:54:37] [Server thread/WARN]: 	at net.aufdemrand.denizencore.utilities.scheduling.RepeatingSchedulable.tick(RepeatingSchedulable.java:20)
[21:54:37] [Server thread/WARN]: 	at net.aufdemrand.denizencore.DenizenCore.tick(DenizenCore.java:139)
[21:54:37] [Server thread/WARN]: 	at net.aufdemrand.denizen.Denizen$2.run(Denizen.java:845)
[21:54:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
[21:54:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[21:54:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679)
[21:54:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335)
[21:54:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628)
[21:54:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536)
[21:54:37] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:54:37] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1m(Attempted: GIVE "i@wool" 
                   "to:<player.open_inventory>") [m
[21:54:37] [Server thread/INFO]: [0;35;1m+---------------------+ [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mCompleting queue 'COMBO_LOCK_HANDLER_BishopPrairieLexmark' in 
                   148ms. [m
[21:54:37] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mEvent[0;30;1m': [0;30;1mType='[0;33;1mon player clicks in inventory[0;30;1m'  
                   [0;30;1mContainer='[0;36;1mCOMBO_LOCK_HANDLER[0;33;1m(WORLD)[0;30;1m'  
                   player=p@zozer_firehood[0;30;1mContext='[0;33;1m{item=i@stone_button[display_name=3], 
                   cursor_item=i@air, raw_slot=4, is_shift_click=false, 
                   slot_type=CRAFTING, action=PICKUP_ALL, slot=4, 
                   inventory=in@COMBO_LOCK, click=LEFT, hotbar_button=-1}[0;30;1m' [m
[21:54:37] [Server thread/INFO]: [0;35;1m+- Building event 'ON PLAYER CLICKS IN INVENTORY' for 
                   COMBO_LOCK_HANDLER ---------+ [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mStarting InstantQueue 
                   'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands'... [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mQueue 'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands' 
                   Executing: IF "<c.inventory.is[!=].to[in@combo_lock]>" "{" "-" 
                   "queue" "clear" "}" [m
[21:54:37] [Server thread/INFO]: [0;35;1m+- Executing dCommand: IF/p@zozer_firehood ---------+ [m
[21:54:37] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mIF[0;30;1m': [0;30;1muse_braces='[0;33;1mtrue[0;30;1m' [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mFilled tag <c.inventory.is[!=].to[in@combo_lock]> with 
                   'false'. [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mQueue 'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands' 
                   Executing: DETERMINE "passively" "CANCELLED" [m
[21:54:37] [Server thread/INFO]: [0;35;1m+- Executing dCommand: DETERMINE/p@zozer_firehood ---------+ [m
[21:54:37] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mDETERMINE[0;30;1m': outcome='[0;36;1mCANCELLED[0;30;1m'  
                   passively='[0;36;1mtrue[0;30;1m' [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mQueue 'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands' 
                   Executing: IF "<c.item.is[==].to[<c.inventory.slot[1]>]>" "{" 
                   "-" "inventory" "close" "d:<c.inventory>" "-" "if" 
                   "<player.flag[unlock_dcl].as_list.is[==].to[<yaml[dcl].read[keys.<player.flag[loc_dcl]>]>]>" 
                   "{" "-" "narrate" "<green>unlocked, you can use this button 
                   for 1 minute" "-" "flag" "player" 
                   "pass_dcl:<player.flag[loc_dcl]>" "duration:1m" "}" "else" "{" 
                   "-" "narrate" "<red>incorrect password" "}" "-" "flag" 
                   "player" "loc_dcl:!" "}" "else" "{" "-" "... * snip! * [m
[21:54:37] [Server thread/INFO]: [0;35;1m+- Executing dCommand: IF/p@zozer_firehood ---------+ [m
[21:54:37] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mIF[0;30;1m': [0;30;1muse_braces='[0;33;1mtrue[0;30;1m' [m
[21:54:37] [pool-9776-thread-1/INFO]: [0;35;1m [0;37;1mFilled tag <c.inventory.slot[1]> with 
                   'i@stone_button[display_name=enter&co]'. [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mFilled tag 
                   <c.item.is[==].to[i@stone_button[display_name=enter&co]]> with 
                   'false'. [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mQueue 'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands' 
                   Executing: FLAG "<player>" "unlock_dcl:->:<c.item.display>" [m
[21:54:37] [Server thread/INFO]: [0;35;1m+- Executing dCommand: FLAG/p@zozer_firehood ---------+ [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mFilled tag <player> with 
                   'p@cb003d47-22d3-42c1-9c7c-67ac2014b8dd'. [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mFilled tag <c.item.display> with '3'. [m
[21:54:37] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mFLAG[0;30;1m': flag_name='[0;36;1mUNLOCK_DCL[0;30;1m'  
                   [0;30;1mAction/Value='[0;36;1mINSERT[0;33;1m(3)[0;30;1m'  flag_target='[0;36;1mp@zozer_firehood[0;30;1m' [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mQueue 'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands' 
                   Executing: DETERMINE "passively" "CANCELLED:false" [m
[21:54:37] [Server thread/INFO]: [0;35;1m+- Executing dCommand: DETERMINE/p@zozer_firehood ---------+ [m
[21:54:37] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mDETERMINE[0;30;1m': outcome='[0;36;1mCANCELLED:false[0;30;1m'  
                   passively='[0;36;1mtrue[0;30;1m' [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mQueue 'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands' 
                   Executing: WAIT "1t" [m
[21:54:37] [Server thread/INFO]: [0;35;1m+- Executing dCommand: WAIT/p@zozer_firehood ---------+ [m
[21:54:37] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mWAIT[0;30;1m': 
                   [0;30;1mqueue='[0;33;1mCOMBO_LOCK_HANDLER_EfficiencyUsuallyIslands[0;30;1m'  
                   delay='[0;36;1md@1t[0;30;1m' [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mForcing queue COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands 
                   into a timed queue... [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mCompleting queue 
                   'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands' in 3ms. [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mStarting TimedQueue 
                   'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands'... [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mQueue 'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands' 
                   Executing: INVENTORY "set" "o:i@air" "d:<c.inventory>" 
                   "slot:1" [m
[21:54:37] [Server thread/INFO]: [0;35;1m+- Executing dCommand: INVENTORY/p@zozer_firehood ---------+ [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mFilled tag <c.inventory> with 'in@COMBO_LOCK'. [m
[21:54:37] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mINVENTORY[0;30;1m': [0;30;1mactions='[0;33;1m[set][0;30;1m'  
                   [0;30;1mdestination='[0;33;1min@COMBO_LOCK[0;30;1m'  
                   [0;30;1morigin='[0;33;1min@generic[size=54;title=Chest][0;30;1m'  slot='[0;36;1m1[0;30;1m' [m
[21:54:37] [Server thread/INFO]: [0;35;1m [0;37;1mQueue 'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands' 
                   Executing: WAIT "1t" [m
[21:54:37] [Server thread/INFO]: [0;35;1m+- Executing dCommand: WAIT/p@zozer_firehood ---------+ [m
[21:54:37] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mWAIT[0;30;1m': 
                   [0;30;1mqueue='[0;33;1mCOMBO_LOCK_HANDLER_EfficiencyUsuallyIslands[0;30;1m'  
                   delay='[0;36;1md@1t[0;30;1m' [m
[21:54:38] [Server thread/INFO]: [0;35;1m [0;37;1mQueue 'COMBO_LOCK_HANDLER_EfficiencyUsuallyIslands' 
                   Executing: GIVE "i@wool" "to:<player.open_inventory>" [m
[21:54:38] [Server thread/INFO]: [0;35;1m+- Executing dCommand: GIVE/p@zozer_firehood ---------+ [m
[21:54:38] [Server thread/INFO]: [0;35;1m [0;37;1mFilled tag <player.open_inventory> with 
                   'in@generic[holder=WORKBENCH;contents=li@i@stone_button[display_name=enter&co]|i@stone_button[display_name=1]|i@stone_button[display_name=2]|i@stone_button[display_name=3]|i@stone_button[display_name=4]|i@stone_button[display_name=5]|i@stone_button[display_name=6]|i@stone_button[display_name=7]|i@stone_button[display_name=8]|i@stone_button[display_name=9];title=Crafting]'. [m
[21:54:38] [Server thread/INFO]: [0;33;1m+> [0;30;1mExecuting '[0;33;1mGIVE[0;30;1m': [0;30;1mType='[0;33;1mITEM[0;30;1m'  
                   [0;30;1minventory='[0;33;1min@generic[holder=WORKBENCH;contents=li@i@stone_button[display_name=enter&co]|i@stone_button[display_name=1]|i@stone_button[display_name=2]|i@stone_button[display_name=3]|i@stone_button[display_name=4]|i@stone_button[display_name=5]|i@stone_button[display_name=6]|i@stone_button[display_name=7]|i@stone_button[display_name=8]|i@stone_button[display_name=9];title=Crafting][0;30;1m' 
                    [0;30;1mQuantity='[0;33;1m1.0[0;30;1m'  engrave='[0;36;1mfalse[0;30;1m'  unlimit_stack_size='[0;36;1mfalse[0;30;1m'  
                   [0;30;1mItems='<Y... * snip! * [m
[21:54:38] [Server thread/INFO]: [0;35;1m [0;37;1mThe inventory didn't have enough space, the rest of the items 
                   have been placed on the floor. [m
[21:54:38] [Server thread/INFO]: [0;35;1m [0;31;1mERROR in script 'COMBO_LOCK_HANDLER'! [0;37;1mWoah!! An exception has 
                   been called with this command! [m
[21:54:38] [Server thread/INFO]: [0;35;1m [0;31;1mERROR in script 'COMBO_LOCK_HANDLER'! [0;37;1mInternal exception was 
                   thrown! [m
[21:54:38] [Server thread/WARN]: java.lang.NullPointerException
[21:54:38] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.commands.item.GiveCommand.execute(GiveCommand.java:152)
[21:54:38] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:236)
[21:54:38] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:52)
[21:54:38] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:655)
[21:54:38] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue.access$000(TimedQueue.java:12)
[21:54:38] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue$1.run(TimedQueue.java:151)
[21:54:38] [Server thread/WARN]: 	at net.aufdemrand.denizencore.utilities.scheduling.RepeatingSchedulable.tick(RepeatingSchedulable.java:20)
[21:54:38] [Server thread/WARN]: 	at net.aufdemrand.denizencore.DenizenCore.tick(DenizenCore.java:139)
[21:54:38] [Server thread/WARN]: 	at net.aufdemrand.denizen.Denizen$2.run(Denizen.java:845)
[21:54:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
[21:54:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[21:54:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679)
[21:54:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335)
[21:54:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628)
[21:54:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536)
[21:54:38] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:54:38] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1m(Attempted: GIVE "i@wool" 
                   "to:<player.open_inventory>") [m
[21:54:38] [Server thread/INFO]: [0;35;1m+---------------------+ [m
```

**Comment by Talamar1** [comment]
uh...use proper syntax and the right argument and avoid the extra crap
- inventory swap o:li@i@wool d:<c.inventory> slot:1

and don't do the give command.

**Comment by zozer** [comment]
where am i supposed to put the determine fulfilled? i never needed it before beside in on command events?

**Comment by Talamar1** [comment]
ignore me, I was coding too much that day in command events...

**Comment by Fortifier42** [comment]
Please close this if it is solved

**Comment by zozer** [comment]
its not...

**Comment by Fortifier42** [comment]
You.. we're trying to give items to a workbench with the give command -

As talamar said, use the right command (inventory)

`- inventory set o:i@wool d:<player.open_inventory> slot:1`

**Comment by Fortifier42** [comment]
@zozer this has been solved...

**Comment by zozer** [comment]
so how do i force an update for the crafting table, since i can't see the wool?

**Comment by Fortifier42** [comment]
You can't. It updates when a recipe is formed :)

**Comment by Fortifier42** [comment]
@mcmonkey4eva @Morphan1 Possible improvement?

**Comment by mcmonkey4eva** [comment]
`- inventory update` might force it to show

**Comment by zozer** [comment]
that throws an error saying only player inventories can be updated

**Comment by mcmonkey4eva** [comment]
Did you... you did something wrong then, for example, not inputting the command exactly as I gave it...

**Comment by zozer** [comment]
when i do it exactly as you said, it assumes i am talking about my inventory, and updates my inventory, so i added 'd:<c.inventory>' and it threw an error: Only player inventories can be force-updated!

**Comment by mcmonkey4eva** [comment]
It /should/ update your inventory... that generally causes the other inventories to update as well. If that doesn't work... well, I'm out of ideas...

**Comment by mcmonkey4eva** [comment]
Is this still an issue?
Comment below to reopen.

**Comment by zozer** [comment]
i couldn't get it to work, though i stopped trying, maybe i will reopen it in the future after playing around with my script some more
