### ISSUE TITLE
Shutdown throwing java error...

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1197]
```
[17:58:26 INFO]: [Citizens] Disabling Citizens v2.0.16-SNAPSHOT (build 1260)
[17:58:26 WARN]: java.lang.NullPointerException
[17:58:26 WARN]:        at net.aufdemrand.denizen.npc.traits.SittingTrait.onDespawn(SittingTrait.java:45)
[17:58:26 WARN]:        at net.citizensnpcs.Citizens.despawnNPCs(Citizens.java:110)
[17:58:26 WARN]:        at net.citizensnpcs.Citizens.onDisable(Citizens.java:249)
[17:58:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
[17:58:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
[17:58:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[17:58:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[17:58:26 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336)
[17:58:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460)
[17:58:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:592)
[17:58:26 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by mcmonkey4eva** [comment]
Third time's the charm! Replication steps?

**Comment by Talamar1** [comment]
every time I shutdown....

**Comment by Talamar1** [comment]
```
[22:50:48 INFO]: [WorldGuard] Disabling WorldGuard v6.1.1-SNAPSHOT.1628-e28b236
[22:50:48 INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[22:50:48 WARN]: Exception in thread "Craft Scheduler Thread - 12"
[22:50:48 WARN]: org.apache.commons.lang.UnhandledException: Plugin Citizens v2.0.16-SNAPSHOT (build 1262) generated aexception while executing task 57
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: no implementation set
        at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:70)
        at net.citizensnpcs.api.CitizensAPI.getPlugin(CitizensAPI.java:110)
        at net.citizensnpcs.npc.profile.ProfileRequest.setResult(ProfileRequest.java:108)
        at net.citizensnpcs.npc.profile.ProfileFetcher$1.onProfileLookupSucceeded(ProfileFetcher.java:93)
        at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileReposity.java:59)
        at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:47)
        at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:88)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

[22:50:48 INFO]: [PlotMe-DefaultGenerator] Disabling PlotMe-DefaultGenerator v0.16.1
```

**Comment by mcmonkey4eva** [comment]
Now that there is a Citizens error :) make sure you're running latest C2 and report there if it continues.
