### ISSUE TITLE
Latest build throws error on every login

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1247]
Updated Cit and Denizen to latest dev builds and get this on every login:
```
[15:41:07 INFO]: UUID of player Talamar1 is 73432797-4d23-4ced-8ef1-c99e84aef77a
[15:41:07 INFO]:  ERROR! Internal exception was thrown!
[15:41:07 WARN]: java.lang.RuntimeException: java.lang.IllegalAccessException: Class net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn can not access a member of class net.minecraft.server.v1_8_R3.PlayerConnection with modifiers "private volatile"
[15:41:07 WARN]:        at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.<init>(AtomicIntegerFieldUpdater.java:284)
[15:41:07 WARN]:        at java.util.concurrent.atomic.AtomicIntegerFieldUpdater.newUpdater(AtomicIntegerFieldUpdater.java:76)
[15:41:07 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.<init>(AbstractListenerPlayIn.java:29)
[15:41:07 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenPacketListener.<init>(DenizenPacketListener.java:24)
[15:41:07 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenNetworkManager.<init>(DenizenNetworkManager.java:25)
[15:41:07 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenNetworkManager.setNetworkManager(DenizenNetworkManager.java:32)
[15:41:07 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenPacketListener$PlayerEventListener.onPlayerJoin(DenizenPacketListener.java:95)
[15:41:07 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:41:07 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[15:41:07 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:41:07 WARN]:        at java.lang.reflect.Method.invoke(Method.java:606)
[15:41:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[15:41:07 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:41:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[15:41:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[15:41:07 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[15:41:07 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[15:41:07 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[15:41:07 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[15:41:07 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[15:41:07 WARN]:        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[15:41:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[15:41:07 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:41:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:41:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:41:07 WARN]:        at java.lang.Thread.run(Thread.java:745)
[15:41:07 WARN]: Caused by: java.lang.IllegalAccessException: Class net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn can not access a member of class net.minecraft.server.v1_8_R3.PlayerConnection with modifiers "private volatile"
[15:41:07 WARN]:        at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:110)
[15:41:07 WARN]:        at sun.reflect.misc.ReflectUtil.ensureMemberAccess(ReflectUtil.java:103)
[15:41:07 WARN]:        at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.<init>(AtomicIntegerFieldUpdater.java:280)
[15:41:07 WARN]:        ... 25 more
[15:41:07 INFO]: Talamar1[/192.168.0.2:42190] logged in with entity id 94 at ([world]1043.0, 134.0, 10028.0)
```

**Comment by mcmonkey4eva** [comment]
@Morphan1 0.o

**Comment by Morphan1** [comment]
@Talamar1 try this https://dl.dropboxusercontent.com/u/188921928/denizen-0.9.7-SNAPSHOT.jar
I hate Atomic fields and I basically decided to murder it, no idea how well it'll work

**Comment by Talamar1** [comment]
That fixed it.
