### ISSUE TITLE
ActionBar

### ISSUE THREAD

**Issue by aleshkanet** [DenizenScript/Denizen-For-Bukkit#1380]
```
[13:29:27 INFO]: [Compassance] ActionBar reflection success.
[13:29:27 WARN]: java.lang.NoSuchMethodException: net.aufdemrand.denizen.utilities.packets.intercept.DenizenPacketListener.sendPacke
[13:29:27 WARN]:        at java.lang.Class.getDeclaredMethod(Class.java:2130)
[13:29:27 WARN]:        at com.hexragon.compassance.utils.ActionBar.send(ActionBar.java:81)
[13:29:27 WARN]:        at com.hexragon.compassance.managers.themes.replacers.ReplacersTheme.displayTo(ReplacersTheme.java:131)
[13:29:27 WARN]:        at com.hexragon.compassance.managers.tasks.CompassTask.run(CompassTask.java:83)
[13:29:27 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[13:29:27 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[13:29:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[13:29:27 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[13:29:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[13:29:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[13:29:27 WARN]:        at java.lang.Thread.run(Thread.java:745)
[13:29:27 ERROR]: [Compassance] Warning! ActionBar execution failed. Reflection functions threw an exception.

```

**Comment by Morphan1** [comment]
That second line (the only one with reference to us) is not complete. Regardless, you are using a 1.8 server. The latest Denizen is 1.9
