### ISSUE TITLE
"/ex compass reset" command crashing

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1388]
```
[01:55:48 INFO]: +- Executing dCommand: COMPASS/p@Eto_Ravengard ---------+ 
[01:55:48 INFO]:  ERROR! Woah!! An exception has been called with this command! 
[01:55:48 INFO]:  ERROR! Internal exception was thrown! 
[01:55:48 WARN]: java.lang.NullPointerException
[01:55:48 WARN]:        at net.aufdemrand.denizen.scripts.commands.player.CompassCommand.execute(CompassCommand.java:61)
[01:55:48 WARN]:        at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:247)
[01:55:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[01:55:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:677)
[01:55:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[01:55:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:508)
[01:55:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:527)
[01:55:48 WARN]:        at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1184)
[01:55:48 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[01:55:48 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[01:55:48 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[01:55:48 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[01:55:48 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[01:55:48 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[01:55:48 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[01:55:48 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[01:55:48 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:55:48 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:55:48 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[01:55:48 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[01:55:48 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[01:55:48 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[01:55:48 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[01:55:48 WARN]:        at java.lang.Thread.run(Thread.java:745)
[01:55:48 INFO]: +> [Denizen] (Attempted: COMPASS "reset") 
[01:55:48 INFO]: +---------------------+ 
[01:55:48 INFO]:  Completing queue 'EXCOMMAND_DenizenConverterOrganisation' in 0ms.
```
Using latest Denizen 1.8.8

**Comment by mcmonkey4eva** [comment]
Corrected. Thanks for the report!
