### ISSUE TITLE
"oxygen 0" command error

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1395]
Hello,

using oxygen command in a script, i've an error:

```
[02:56:27 WARN]: java.lang.IllegalArgumentException: No enum constant net.aufdemrand.denizen.scripts.commands.player.OxygenCommand.Mode.REMAINING
[02:56:27 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[02:56:27 WARN]:        at net.aufdemrand.denizen.scripts.commands.player.OxygenCommand$Mode.valueOf(OxygenCommand.java:17)
[02:56:27 WARN]:        at net.aufdemrand.denizen.scripts.commands.player.OxygenCommand.execute(OxygenCommand.java:81)
[02:56:27 WARN]:        at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:247)
[02:56:27 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[02:56:27 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:677)
[02:56:27 WARN]:        at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[02:56:27 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:508)
[02:56:27 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:527)
[02:56:27 WARN]:        at net.aufdemrand.denizencore.events.ScriptEvent.run(ScriptEvent.java:273)
[02:56:27 WARN]:        at net.aufdemrand.denizencore.events.ScriptEvent.fire(ScriptEvent.java:241)
[02:56:27 WARN]:        at net.aufdemrand.denizen.events.player.PlayerWalkScriptEvent.onPlayerMoves(PlayerWalkScriptEvent.java:105)
[02:56:27 WARN]:        at sun.reflect.GeneratedMethodAccessor433.invoke(Unknown Source)
[02:56:27 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:56:27 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[02:56:27 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[02:56:27 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:56:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[02:56:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[02:56:27 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)
[02:56:27 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)
[02:56:27 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[02:56:27 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[02:56:27 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[02:56:27 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02:56:27 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[02:56:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[02:56:27 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[02:56:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[02:56:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[02:56:27 WARN]:        at java.lang.Thread.run(Thread.java:745)
[02:56:27 INFO]: +> [Denizen] (Attempted: OXYGEN "0") 
```
Using 1.8.8 latest

**Comment by mcmonkey4eva** [comment]
Can you replicate this in 1.9.2?

Also, try: `- oxygen 0 type:remaining mode:set`

**Comment by Xenmai** [comment]
Here:

`Java Version: 1.8.0_51 
Up-time: 5m 27s 
CraftBukkit Version: git-Spigot-5a40365-f631379 (MC: 1.9.2) 
Denizen Version: Core: 1.10 (Build Unknown), CraftBukkit: 0.9.8-SNAPSHOT (build 565) 
Active Plugins (2): Citizens: 2.0.17-SNAPSHOT (build 1355), Denizen: 0.9.8-SNAPSHOT (build 565), 
Loaded Worlds (3): world, world_nether, world_the_end 
Online Players (1): xenmai(xenmai) 
Offline Players: 2 
Mode: online 

15:22:51 [INFO]  Starting InstantQueue 'EXCOMMAND_RoundsStandingMembrane'...  
15:22:51 [INFO]  Queue 'EXCOMMAND_RoundsStandingMembrane' Executing: OXYGEN  
                   "0" "type:remaining" "mode:set"  
15:22:51 [INFO] +- Executing dCommand: OXYGEN/p@xenmai ---------+  
15:22:51 [INFO] +> Executing 'OXYGEN': type='remaining'  mode='set'   
                   amount='0'  
15:22:51 [INFO]  ERROR! Woah!! An exception has been called with this command!  
15:22:51 [INFO]  ERROR! Internal exception was thrown!  
15:22:51 [SEVERE] java.lang.IllegalArgumentException: No enum constant net.aufdemrand.denizen.scripts.commands.player.OxygenCommand.Mode.REMAINI 
NG 
15:22:51 [SEVERE] java.lang.Enum.valueOf(Unknown Source) 
15:22:51 [SEVERE] net.aufdemrand.denizen.scripts.commands.player.OxygenCommand$Mode.valueOf(OxygenCommand.java:17) 
15:22:51 [SEVERE] net.aufdemrand.denizen.scripts.commands.player.OxygenCommand.execute(OxygenCommand.java:81) 
15:22:51 [SEVERE] net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:247) 
15:22:51 [SEVERE] net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54) 
15:22:51 [SEVERE] net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:677) 
15:22:51 [SEVERE] net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61) 
15:22:51 [SEVERE] net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:508) 
15:22:51 [SEVERE] net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:527) 
15:22:51 [SEVERE] net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1217) 
15:22:51 [SEVERE] org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) 
15:22:51 [SEVERE] org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) 
15:22:51 [SEVERE] org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) 
15:22:51 [SEVERE] net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) 
15:22:51 [SEVERE] net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) 
15:22:51 [SEVERE] net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) 
15:22:51 [SEVERE] net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) 
15:22:51 [SEVERE] net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) 
15:22:51 [SEVERE] java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 
15:22:51 [SEVERE] java.util.concurrent.FutureTask.run(Unknown Source) 
15:22:51 [SEVERE] net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) 
15:22:51 [SEVERE] net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) 
15:22:51 [SEVERE] net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) 
15:22:51 [SEVERE] net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) 
15:22:51 [SEVERE] net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) 
15:22:51 [SEVERE] java.lang.Thread.run(Unknown Source) 
15:22:51 [INFO] +> [Denizen] (Attempted: OXYGEN "0" "type:remaining"  
                   "mode:set")  
15:22:51 [INFO] +---------------------+  
15:22:51 [INFO]  Completing queue 'EXCOMMAND_RoundsStandingMembrane' in 13ms.`

**Comment by mcmonkey4eva** [comment]
Fixed for next build. Thanks!
