### ISSUE TITLE
if indentation

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1406]
Hello,

I try to announce a message on player's death when a mythicmob is the damager.
Here the script:

```
test_mm_ondeath_2:
    type: world
    debug: true
    events:
        on player death:
        - if <context.damager.is_mythicmob> {
            - determine "<&c>[<&4>Meurt!<&c>] <&d><context.entity.player.name> <&c>s'est fait trucidé par un <context.damager.mythicmob.internal_name> <&6>[Lvl.<context.damager.mythicmob.level>] <&2>(<context.damager.mythicmob.entity.health.round>/<context.damager.mythicmob.entity.health.max.round>)"
        }
```

And here the log:

```
[16:47:40 INFO]: +- Executing dCommand: IF/p@MrMaleficus ---------+ 
[16:47:40 INFO]: +> Executing 'IF': use_braces='true' 
[16:47:40 INFO]:  Filled tag <context.damager.is_mythicmob> with 'true'. 
[16:47:40 INFO]:  ERROR in script 'TEST_MM_TEST2'! Woah!! An exception has been called with this command! 
[16:47:40 INFO]:  ERROR in script 'TEST_MM_TEST2'! Internal exception was thrown! 
[16:47:40 WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[16:47:40 WARN]:    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
[16:47:40 WARN]:    at java.util.ArrayList.get(ArrayList.java:429)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.commands.core.IfCommand.execute(IfCommand.java:112)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:247)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:677)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:508)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:527)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.events.ScriptEvent.run(ScriptEvent.java:273)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.events.ScriptEvent.fire(ScriptEvent.java:241)
[16:47:40 WARN]:    at net.aufdemrand.denizen.events.entity.EntityDeathScriptEvent.onEntityDeath(EntityDeathScriptEvent.java:245)
[16:47:40 WARN]:    at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source)
[16:47:40 WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:47:40 WARN]:    at java.lang.reflect.Method.invoke(Method.java:498)
[16:47:40 WARN]:    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:47:40 WARN]:    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:47:40 WARN]:    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:47:40 WARN]:    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:47:40 WARN]:    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396)
[16:47:40 WARN]:    at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:417)
[16:47:40 WARN]:    at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812)
[16:47:40 WARN]:    at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800)
[16:47:40 WARN]:    at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496)
[16:47:40 WARN]:    at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.damage(CraftLivingEntity.java:241)
[16:47:40 WARN]:    at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.damage(CraftLivingEntity.java:229)
[16:47:40 WARN]:    at net.aufdemrand.denizen.scripts.commands.entity.HurtCommand.execute(HurtCommand.java:108)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:247)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:677)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue.access$000(TimedQueue.java:12)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue$1.run(TimedQueue.java:154)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.utilities.scheduling.RepeatingSchedulable.tick(RepeatingSchedulable.java:20)
[16:47:40 WARN]:    at net.aufdemrand.denizencore.DenizenCore.tick(DenizenCore.java:151)
[16:47:40 WARN]:    at net.aufdemrand.denizen.Denizen$2.run(Denizen.java:863)
[16:47:40 WARN]:    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[16:47:40 WARN]:    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[16:47:40 WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[16:47:40 WARN]:    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:47:40 WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:47:40 WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:47:40 WARN]:    at java.lang.Thread.run(Thread.java:745)
[16:47:40 INFO]: +> [Denizen] (Attempted: IF "<context.damager.is_mythicmob>" "{") 
[16:47:40 INFO]: +---------------------+ 
[16:47:40 INFO]:  Queue 'TEST_MM_TEST2_InstallationsBeatLatina' Executing: DETERMINE "<&c>[<&4>Meurt!<&c>] <&d><context.entity.player.name> <&c>s'est fait trucidé par un 
                   <context.damager.mythicmob.internal_name> <&6>[Lvl.<context.damager.mythicmob.level>] 
                   <&2>(<context.damager.mythicmob.entity.health.round>/<context.damager.mythicmob.entity.health.max.round>)" "}" 
[16:47:40 INFO]: +- Executing dCommand: DETERMINE/p@MrMaleficus ---------+ 
[16:47:40 INFO]:  Filled tag <&c> with ''. 
[16:47:40 INFO]:  Filled tag <&4> with ''. 
[16:47:40 INFO]:  Filled tag <&c> with ''. 
[16:47:40 INFO]:  Filled tag <&d> with ''. 
[16:47:40 INFO]:  Unfilled attributes '[player, name]' for tag <context.entity.player.name>! 
[16:47:40 INFO]:  Filled tag <context.entity.player.name> with 'MrMaleficus'. 
[16:47:40 INFO]:  Filled tag <&c> with ''. 
[16:47:40 INFO]:  Filled tag <context.damager.mythicmob.internal_name> with 'Bandit'. 
[16:47:40 INFO]:  Filled tag <&6> with ''. 
[16:47:40 INFO]:  Filled tag <context.damager.mythicmob.level> with '5'. 
[16:47:40 INFO]:  Filled tag <&2> with ''. 
[16:47:40 INFO]:  Filled tag <context.damager.mythicmob.entity.health.round> with '24'. 
[16:47:40 INFO]:  Filled tag <context.damager.mythicmob.entity.health.max.round> with '25'. 
[16:47:40 INFO]:  ERROR! '}' is an unknown argument! 
```

The script works, it display the correct announce with all tags filled, but there is this (useless?) error.

**Comment by mcmonkey4eva** [comment]
I don't think that script lines up with the debug. The debug says there was an indentation error...
