### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by renzotom** [DenizenScript/Denizen-For-Bukkit#1415]
```
[16:16:05] [Server thread/ERROR]: Could not load 'plugins/denizen-0.9.8-SNAPSHOT (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/LoggerOutputStream
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/LoggerOutputStream
	at net.aufdemrand.denizen.Denizen.<clinit>(Denizen.java:270) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_9_R1.LoggerOutputStream
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	at net.aufdemrand.denizen.Denizen.<clinit>(Denizen.java:270) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	... 6 more
```

**Comment by mcmonkey4eva** [comment]
Update to latest dev build for experimental 1.9.4 support: http://ci.mineconomy.org/job/Denizen_Developmental/

**Comment by Shalintan** [comment]
hello. I have a similar problem : 

tested with latest experimental version (#583) 

[15:07:27] [Server thread/ERROR]: Could not load 'plugins/denizen-0.9.8-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot.jar:git-Spigot-4af49dc-4e19de1]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-4af49dc-4e19de1]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-4af49dc-4e19de1]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot.jar:git-Spigot-4af49dc-4e19de1]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot.jar:git-Spigot-4af49dc-4e19de1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_91]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_91]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_91]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_91]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot.jar:git-Spigot-4af49dc-4e19de1]
	... 5 more
