### ISSUE TITLE
Denizen not loading

### ISSUE THREAD

**Issue by Shalintan** [DenizenScript/Denizen-For-Bukkit#1416]
hello. here is the problem :
CraftBukkit version git-Spigot-4af49dc-4e19de1 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
tested with latest experimental version (#583)
```
[15:07:27] [Server thread/ERROR]: Could not load 'plugins/denizen-0.9.8-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot.jar:git-Spigot-4af49dc-4e19de1]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-4af49dc-4e19de1]
at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-4af49dc-4e19de1]
at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot.jar:git-Spigot-4af49dc-4e19de1]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot.jar:git-Spigot-4af49dc-4e19de1]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_91]
at java.util.zip.ZipFile.(ZipFile.java:219) ~[?:1.8.0_91]
at java.util.zip.ZipFile.(ZipFile.java:149) ~[?:1.8.0_91]
at java.util.jar.JarFile.(JarFile.java:166) ~[?:1.8.0_91]
at java.util.jar.JarFile.(JarFile.java:130) ~[?:1.8.0_91]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot.jar:git-Spigot-4af49dc-4e19de1]
... 5 more
```

**Comment by Morphan1** [comment]
Your download was corrupted. Try re-downloading

**Comment by Shalintan** [comment]
You are right ! It's strange because the file was downloaded from two different computers (then uploaded with sftp with same issue. 
Tried now direclty from the server and it's ok... Both machines running Eset Nod 32 security. Maybe it's the cause. Thanks for you reply
