### ISSUE TITLE
light command bug

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1417]
Hello,
Got this error while executing the light command in Denizen

```
[12:00:43 INFO]:  ERROR! Internal exception was thrown! 
[12:00:43 WARN]: java.lang.NullPointerException
[12:00:43 WARN]:        at net.aufdemrand.denizen.utilities.blocks.BlockLight.getPlayerChunk(BlockLight.java:213)
[12:00:43 WARN]:        at net.aufdemrand.denizen.utilities.blocks.BlockLight.updateChunk(BlockLight.java:202)
[12:00:43 WARN]:        at net.aufdemrand.denizen.utilities.blocks.BlockLight.update(BlockLight.java:192)
[12:00:43 WARN]:        at net.aufdemrand.denizen.utilities.blocks.BlockLight.reset(BlockLight.java:160)
[12:00:43 WARN]:        at net.aufdemrand.denizen.utilities.blocks.BlockLight.removeLight(BlockLight.java:132)
[12:00:43 WARN]:        at net.aufdemrand.denizen.scripts.commands.world.LightCommand.execute(LightCommand.java:80)
[12:00:43 WARN]:        at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:248)
[12:00:43 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[12:00:43 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:678)
[12:00:43 WARN]:        at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[12:00:43 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:509)
[12:00:43 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:528)
[12:00:43 WARN]:        at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1219)
[12:00:43 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:00:43 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:00:43 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:645)
[12:00:43 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349)
[12:00:43 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184)
[12:00:43 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:00:43 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:00:43 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[12:00:43 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:00:43 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:00:43 WARN]:        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[12:00:43 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726)
[12:00:43 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[12:00:43 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[12:00:43 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[12:00:43 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

Using latest Developmental and Spigot 1.9.4

Thank you :)

**Comment by mcmonkey4eva** [comment]
Yup, this is a live bug with 1.9.4, we're waiting on @Morphan1 for this.

**Comment by Morphan1** [comment]
#1405
