### ISSUE TITLE
Error 500 stats recording

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1419]
Hello,

Just got this error each hour since this morning without reason:

```
[12:35:36 INFO]:  ERROR! Internal exception was thrown! 
[12:35:36 WARN]: java.io.IOException: Server returned HTTP response code: 500 for URL: http://neo.mcmonkey.org/plugins/public_stats?plugin=Denizen&version=0.9.8-SNAPSHOT+%28build+582%29
[12:35:36 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
[12:35:36 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
[12:35:36 WARN]:        at net.aufdemrand.denizen.utilities.debugging.StatsRecord.run(StatsRecord.java:31)
```

Thank you :)

**Comment by mcmonkey4eva** [comment]
Woops. Website fixed.
