### ISSUE TITLE
denizen not load in Spigot 1.9.4

### ISSUE THREAD

**Issue by Culvanen** [DenizenScript/Denizen-For-Bukkit#1420]
```
20.05 21:52:53 [Server] INFO ... 6 more
20.05 21:52:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
20.05 21:52:53 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
20.05 21:52:53 [Server] INFO at net.aufdemrand.denizen.Denizen.<clinit>(Denizen.java:270) ~[?:?]
20.05 21:52:53 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
20.05 21:52:53 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
20.05 21:52:53 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_9_R1.LoggerOutputStream
20.05 21:52:53 [Server] INFO ... 6 more
20.05 21:52:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
20.05 21:52:53 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
20.05 21:52:53 [Server] INFO at net.aufdemrand.denizen.Denizen.<clinit>(Denizen.java:270) ~[?:?]
20.05 21:52:53 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/LoggerOutputStream
20.05 21:52:53 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
20.05 21:52:53 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:296) [Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[Spigot-stb194.jar:git-Spigot-4af49dc-23da8b0]
20.05 21:52:53 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/LoggerOutputStream
20.05 21:52:53 [Server] ERROR Could not load 'plugins/denizen-0.9.8-SNAPSHOT.jar' in folder 'plugins'
```

**Comment by mcmonkey4eva** [comment]
Download developmental 1.9.4 builds at http://ci.mineconomy.org/job/Denizen_Developmental/

**Comment by Culvanen** [comment]
working fine thanks !
