### ISSUE TITLE
Error log on player join

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1423]
Hello,

I've a strange error fired (twice) when a player join the server : 

```
[20:23:30 INFO]: UUID of player MrMaleficus is 7e76edc9-299d-4556-a485-5879015bebc2
[20:23:30 INFO]:  ERROR! Internal exception was thrown! 
[20:23:30 WARN]: java.lang.NullPointerException
[20:23:30 WARN]:        at net.aufdemrand.denizen.utilities.PlayerProfileEditor.updatePlayerProfiles(PlayerProfileEditor.java:75)
[20:23:30 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.PacketOutHandler.sendPacket(PacketOutHandler.java:170)
[20:23:30 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenNetworkManager.sendPacket(DenizenNetworkManager.java:70)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.sendPacket(PlayerConnection.java:1095)
[20:23:30 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.sendPacket(AbstractListenerPlayIn.java:70)
[20:23:30 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenPacketListener.sendPacket(DenizenPacketListener.java:86)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.PlayerList.onPlayerJoin(PlayerList.java:353)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.PlayerList.a(PlayerList.java:159)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.LoginListener.b(LoginListener.java:144)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.LoginListener.c(LoginListener.java:54)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:233)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:140)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:825)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[20:23:30 WARN]:        at java.lang.Thread.run(Thread.java:745)
[20:23:30 INFO]:  ERROR! Internal exception was thrown! 
[20:23:30 WARN]: java.lang.NullPointerException
[20:23:30 WARN]:        at net.aufdemrand.denizen.utilities.PlayerProfileEditor.updatePlayerProfiles(PlayerProfileEditor.java:75)
[20:23:30 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.PacketOutHandler.sendPacket(PacketOutHandler.java:170)
[20:23:30 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenNetworkManager.sendPacket(DenizenNetworkManager.java:70)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.sendPacket(PlayerConnection.java:1095)
[20:23:30 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.sendPacket(AbstractListenerPlayIn.java:70)
[20:23:30 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenPacketListener.sendPacket(DenizenPacketListener.java:86)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.PlayerList.onPlayerJoin(PlayerList.java:360)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.PlayerList.a(PlayerList.java:159)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.LoginListener.b(LoginListener.java:144)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.LoginListener.c(LoginListener.java:54)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:233)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:140)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:825)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[20:23:30 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[20:23:30 WARN]:        at java.lang.Thread.run(Thread.java:745)
[20:23:30 INFO]: MrMaleficus[/109.219.155.119:58390] logged in with entity id 26641 at ([world]651.8977472585674, 102.73087887976811, 738.5593921093564)
```
Using latest dev
Thank you :)

**Comment by mcmonkey4eva** [comment]
@Morphan1 what even is null in
```
                GameProfile gameProfile = (GameProfile) playerInfoData_gameProfile.get(data);
```

**Comment by Morphan1** [comment]
@mcmonkey4eva it's possible `playerInfoData_gameProfile` might be, and an error occurred on startup or somewhere like that. Who knows what `data` might be

**Comment by MrMaleficus** [comment]
Another error has appeared :

```
[01:42:20 INFO]:  ERROR! Internal exception was thrown! 
[01:42:20 WARN]: java.lang.NoSuchFieldException: d
[01:42:20 WARN]:        at java.lang.Class.getDeclaredField(Class.java:2070)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.PlayerProfileEditor.<clinit>(PlayerProfileEditor.java:53)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.PacketOutHandler.sendPacket(PacketOutHandler.java:170)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenNetworkManager.sendPacket(DenizenNetworkManager.java:70)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.sendPacket(PlayerConnection.java:1095)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.sendPacket(AbstractListenerPlayIn.java:70)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenPacketListener.sendPacket(DenizenPacketListener.java:86)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.PlayerList.onPlayerJoin(PlayerList.java:353)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.PlayerList.a(PlayerList.java:159)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.LoginListener.b(LoginListener.java:144)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.LoginListener.c(LoginListener.java:54)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:233)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:140)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:825)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[01:42:20 WARN]:        at java.lang.Thread.run(Thread.java:745)
[01:42:20 INFO]:  ERROR! Internal exception was thrown! 
[01:42:20 WARN]: java.lang.NullPointerException
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.PlayerProfileEditor.updatePlayerProfiles(PlayerProfileEditor.java:75)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.PacketOutHandler.sendPacket(PacketOutHandler.java:170)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenNetworkManager.sendPacket(DenizenNetworkManager.java:70)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.sendPacket(PlayerConnection.java:1095)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.sendPacket(AbstractListenerPlayIn.java:70)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenPacketListener.sendPacket(DenizenPacketListener.java:86)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.PlayerList.onPlayerJoin(PlayerList.java:353)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.PlayerList.a(PlayerList.java:159)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.LoginListener.b(LoginListener.java:144)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.LoginListener.c(LoginListener.java:54)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:233)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:140)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:825)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[01:42:20 WARN]:        at java.lang.Thread.run(Thread.java:745)
[01:42:20 INFO]:  ERROR! Internal exception was thrown! 
[01:42:20 WARN]: java.lang.NullPointerException
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.PlayerProfileEditor.updatePlayerProfiles(PlayerProfileEditor.java:75)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.PacketOutHandler.sendPacket(PacketOutHandler.java:170)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenNetworkManager.sendPacket(DenizenNetworkManager.java:70)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.sendPacket(PlayerConnection.java:1095)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.sendPacket(AbstractListenerPlayIn.java:70)
[01:42:20 WARN]:        at net.aufdemrand.denizen.utilities.packets.intercept.DenizenPacketListener.sendPacket(DenizenPacketListener.java:86)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.PlayerList.onPlayerJoin(PlayerList.java:360)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.PlayerList.a(PlayerList.java:159)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.LoginListener.b(LoginListener.java:144)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.LoginListener.c(LoginListener.java:54)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:233)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:140)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:825)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[01:42:20 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[01:42:20 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

I tried without any scripts and without many plugins, this error is still here :/

**Comment by mcmonkey4eva** [comment]
Check your logs for errors during startup?

**Comment by MrMaleficus** [comment]
No startup errors:  http://mcmonkey.org/haste/33779

**Comment by mcmonkey4eva** [comment]
Released a new build with a potential fix, and:
```
[16:59:16] <MrMaleficus> mcmonkey, it works ! Thank you ! You can close the issue :D
```
