### ISSUE TITLE
Notables do not load or save

### ISSUE THREAD

**Issue by Leoliuos** [DenizenScript/Denizen-For-Bukkit#1435]
Notables don't load from the notables.yml and denizen save doesn't create one either. 

I can add notables and list the new ones I create in a session, but saving denizen, or stopping server doesn't save them anywhere, I've looked through saves, configs etc. if the save logic has changed.

Please confirm if anyone else is having the same issue. If not I will try bringing small pieces one by one to see what's wrong with my own setup. I assume we are still supposed to use notables right, and they aren't replaced by something else?

**Comment by mcmonkey4eva** [comment]
Look in your console or logs files, something should be showing (an error) if it wasn't able to save.

**Comment by Leoliuos** [comment]
Thanks! The problem was using Craftbukkit. I changed to Spigot and notables works now.

Newest CraftBukkit gave this error which probably stopped the loading from denizen:

[13:10:57 WARN]: [Denizen] Task #9 for Denizen v0.9.8-SNAPSHOT (build 1618) gene
rated an exception
java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerItemDamageEvent
        at net.aufdemrand.denizen.events.player.PlayerItemTakesDamageScriptEvent
.destroy(PlayerItemTakesDamageScriptEvent.java:88) ~[?:?]
        at net.aufdemrand.denizencore.events.ScriptEvent.reload(ScriptEvent.java
:86) ~[?:?]
        at net.aufdemrand.denizencore.DenizenCore.loadScripts(DenizenCore.java:1
07) ~[?:?]
        at net.aufdemrand.denizen.Denizen$1.run(Denizen.java:874) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.jav
a:53) ~[craftbukkit.jar:git-Bukkit-9856d8a]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:349) [craftbukkit.jar:git-Bukkit-9856d8a]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:
697) [craftbukkit.jar:git-Bukkit-9856d8a]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:
360) [craftbukkit.jar:git-Bukkit-9856d8a]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:
646) [craftbukkit.jar:git-Bukkit-9856d8a]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:550) [craftbukkit.jar:git-Bukkit-9856d8a]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.player.PlayerItemD
amageEvent
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:67) ~[craftbukkit.jar:git-Bukkit-9856d8a]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:62) ~[craftbukkit.jar:git-Bukkit-9856d8a]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
        ... 11 more
