### ISSUE TITLE
A command return me to "report this error"

### ISSUE THREAD

**Issue by kenjiraw** [DenizenScript/Denizen-For-Bukkit#1443]
java.lang.NoClassDefFoundError:
 org/bukkit/event/player/PlayerItemDamageEvent
```
[15:22:43] [INFO] Kenjiraw issued server command: /denizen reload scripts
[15:22:43] [INFO] +> [Denizen] Processing outside scripts... 
[15:22:43] [INFO] +> [Denizen] Processing unnamed script... 
[15:22:43] [INFO] +> [Denizen] Processing '/mercenariat.yml'... 
[15:22:43] [INFO] OKAY! All scripts loaded! 
[15:22:43] [INFO] +> [Denizen] Adding script MERCENAIRE as type INTERACT 
[15:22:43] [INFO] +> [Denizen] Adding script MERCENARIAT as type ASSIGNMENT 
[15:22:43] [INFO] +> [Denizen] Adding script BUILTIN_LOAD_TESTER as type COMMAND 
[15:22:43] [INFO] +> [Denizen] Scanning 0 world scripts... 
[15:22:43] [INFO] +> [Denizen] Reloading script events... 
[15:22:43] [WARN] java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerItemDamageEvent
[15:22:43] [WARN] at net.aufdemrand.denizen.events.player.PlayerItemTakesDamageScriptEvent.destroy(PlayerItemTakesDamageScriptEvent.java:88)
[15:22:43] [WARN] at net.aufdemrand.denizencore.events.ScriptEvent.reload(ScriptEvent.java:86)
[15:22:43] [WARN] at net.aufdemrand.denizencore.DenizenCore.loadScripts(DenizenCore.java:107)
[15:22:43] [WARN] at net.aufdemrand.denizencore.DenizenCore.reloadScripts(DenizenCore.java:121)
[15:22:43] [WARN] at net.aufdemrand.denizen.DenizenCommandHandler.reload(DenizenCommandHandler.java:441)
[15:22:43] [WARN] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:22:43] [WARN] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:22:43] [WARN] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:22:43] [WARN] at java.lang.reflect.Method.invoke(Method.java:498)
[15:22:43] [WARN] at net.aufdemrand.denizen.utilities.command.CommandManager.executeMethod(CommandManager.java:140)
[15:22:43] [WARN] at net.aufdemrand.denizen.utilities.command.CommandManager.execute(CommandManager.java:66)
[15:22:43] [WARN] at net.aufdemrand.denizen.utilities.command.CommandManager.executeSafe(CommandManager.java:168)
[15:22:43] [WARN] at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1230)
[15:22:43] [WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:22:43] [WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[15:22:43] [WARN] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:625)
[15:22:43] [WARN] at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1299)
[15:22:43] [WARN] at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1159)
[15:22:43] [WARN] at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:37)
[15:22:43] [WARN] at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:9)
[15:22:43] [WARN] at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[15:22:43] [WARN] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:22:43] [WARN] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:22:43] [WARN] at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[15:22:43] [WARN] at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:690)
[15:22:43] [WARN] at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360)
[15:22:43] [WARN] at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:646)
[15:22:43] [WARN] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:550)
[15:22:43] [WARN] at java.lang.Thread.run(Thread.java:745)
```

**Comment by AnthonyAMC** [comment]
What version of denizen are you using? And of spigot?
```
/version
/version denizen
```
You can find the stable version of denizen for your version of spigot [here](http://wiki.citizensnpcs.co/Versions).
Nightly builds can be found [here](http://ci.mineconomy.org/job/Denizen_Developmental/) and are built against the latest version of spigot.

**Comment by mcmonkey4eva** [comment]
@kenjiraw Please ensure you are running **Spigot** not **CraftBukkit**. Bukkit is no longer an active project. Spigot is. Because of this, we target Spigot and use its APIs, not Bukkit's.
