### ISSUE TITLE
factions issue

### ISSUE THREAD

**Issue by Cyborax** [DenizenScript/Denizen-For-Bukkit#1463]
[15:04:53 INFO]:  ERROR! Internal exception was thrown!
[15:04:53 WARN]: java.lang.reflect.InvocationTargetException
[15:04:53 WARN]:        at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)
[15:04:53 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:04:53 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[15:04:53 WARN]:        at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:87)
[15:04:53 WARN]:        at net.aufdemrand.denizen.objects.dNPC.getAttribute(dNPC.java:1076)
[15:04:53 WARN]:        at net.aufdemrand.denizen.tags.core.NPCTags.npcTags(NPCTags.java:81)
[15:04:53 WARN]:        at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
[15:04:53 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:04:53 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[15:04:53 WARN]:        at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:83)
[15:04:53 WARN]:        at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:258)
[15:04:53 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:04:53 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:04:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:04:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:04:53 WARN]:        at java.lang.Thread.run(Thread.java:745)
[15:04:53 WARN]: Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.entity.MPlayerColl.create(Ljava/lang/Object;)Ljava/lang/Object;
[15:04:53 WARN]:        at net.gnomeffinway.depenizen.extensions.factions.FactionsPlayerNPCExtension.<init>(FactionsPlayerNPCExtension.java:41)
[15:04:53 WARN]:        at net.gnomeffinway.depenizen.extensions.factions.FactionsPlayerNPCExtension.getFrom(FactionsPlayerNPCExtension.java:26)
[15:04:53 WARN]:        ... 16 more

**Comment by Cyborax** [comment]
this error occours if i enable
- Faction 2.8.19
- MassiveCore 2.8.19
- FactionsDynmap 2.8.19
- Factions Tax 2.8.19
and only if i also /denizen debug enabled
with 2.8.20 its the same.

**Comment by mcmonkey4eva** [comment]
Depenizen issue: https://github.com/DenizenScript/Depenizen-For-Bukkit/issues

**Comment by Cyborax** [comment]
Thanks for the information ;) i didn't realize that this issue came from depenizen.
Ill disable depenizen for a while.. I just use depenizen for inventory transfer but that seems to have also a problem.
