### ISSUE TITLE
1.0.0 r2 spigot 1.9.4 FishHook entity error

### ISSUE THREAD

**Issue by DNx5** [DenizenScript/Denizen-For-Bukkit#1471]
the error shows when a npc with fishing trait trying to throw the fishing hook.
```
25.09 03:38:02 [Server] INFO [Citizens] Exception while updating 6: Cannot spawn an entity for org.bukkit.entity.FishHook.
25.09 03:38:02 [Server] WARN java.lang.IllegalArgumentException: Cannot spawn an entity for org.bukkit.entity.FishHook
25.09 03:38:02 [Server] WARN at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.createEntity(CraftWorld.java:1180)
25.09 03:38:02 [Server] WARN at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.spawn(CraftWorld.java:1196)
25.09 03:38:02 [Server] WARN at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.spawn(CraftWorld.java:900)
25.09 03:38:02 [Server] WARN at net.aufdemrand.denizen.npc.traits.FishingTrait.cast(FishingTrait.java:180)
25.09 03:38:02 [Server] WARN at net.aufdemrand.denizen.npc.traits.FishingTrait.run(FishingTrait.java:66)
25.09 03:38:02 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
25.09 03:38:02 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:271)
25.09 03:38:02 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.m(EntityHumanNPC.java:303)
25.09 03:38:02 [Server] WARN at net.minecraft.server.v1_9_R2.World.entityJoinedWorld(World.java:1617)
25.09 03:38:02 [Server] WARN at net.minecraft.server.v1_9_R2.World.g(World.java:1592)
25.09 03:38:02 [Server] WARN at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:52)
25.09 03:38:02 [Server] WARN at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
25.09 03:38:02 [Server] WARN at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
25.09 03:38:02 [Server] WARN at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734)
25.09 03:38:02 [Server] WARN at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
25.09 03:38:02 [Server] WARN at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
25.09 03:38:02 [Server] WARN at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
25.09 03:38:02 [Server] WARN at java.lang.Thread.run(Thread.java:745)
```

**Comment by mcmonkey4eva** [comment]
Fishing trait's been a wreck forever now...

**Comment by Morphan1** [comment]
Try the latest developmental build
http://ci.citizensnpcs.co/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by DNx5** [comment]
it fixed the error, but the npc still throws nothing.
