### ISSUE TITLE
Error with custom heads is back

### ISSUE THREAD

**Issue by Cyborax** [DenizenScript/Denizen-For-Bukkit#1472]
```
[09:50:32 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@7a7acabe[id=9dd42c6b-0732-3aee-ba4c-e695d1d351ac,name=-msd-,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[spigot1102.jar:git-Spigot-570526c-6af9f5b]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [spigot1102.jar:git-Spigot-570526c-6af9f5b]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) [spigot1102.jar:git-Spigot-570526c-6af9f5b]
        at net.aufdemrand.denizen.nms.Handler_v1_10_R1.fillPlayerProfile(Handler_v1_10_R1.java:155) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.objects.properties.item.ItemSkullskin.adjust(ItemSkullskin.java:160) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.objects.dItem.adjust(dItem.java:1083) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.objects.dItem.applyProperty(dItem.java:1075) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizencore.objects.ObjectFetcher.getObjectFrom(ObjectFetcher.java:164) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.objects.dItem.valueOf(dItem.java:82) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.objects.dItem.valueOf(dItem.java:53) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.objects.dItem.valueOf(dItem.java:47) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.scripts.containers.core.ItemScriptContainer.getItemFrom(ItemScriptContainer.java:162) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.objects.dItem.valueOf(dItem.java:113) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.objects.dItem.valueOf(dItem.java:56) [denizen-1.0.0-SNAPSHOT.jar:?]
        at sun.reflect.GeneratedMethodAccessor185.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
        at net.aufdemrand.denizencore.objects.ObjectFetcher.getObjectFrom(ObjectFetcher.java:156) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizencore.objects.dList.filter(dList.java:236) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.objects.dInventory.getAttribute(dInventory.java:1638) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.objects.dPlayer.getAttribute(dPlayer.java:1452) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizen.tags.core.PlayerTags.playerTags(PlayerTags.java:90) [denizen-1.0.0-SNAPSHOT.jar:?]
        at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
        at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:83) [denizen-1.0.0-SNAPSHOT.jar:?]
        at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:258) [denizen-1.0.0-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

**Comment by mcmonkey4eva** [comment]
`The client has sent too many requests within a certain amount of time`

**Comment by Cyborax** [comment]
i know you already fixed that with an earlier version. this error occours if i create or use items like this:

`lucky_box:
    type: item
    debug: false    
    material: human_skull[skull_skin=0e037952-99cb-4690-b305-ef25f6ce1125|eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjNiNzEwYjA4YjUyM2JiYTdlZmJhMDdjNjI5YmEwODk1YWQ2MTEyNmQyNmM4NmJlYjM4NDU2MDNhOTc0MjZjIn19fQ==|-lukb-]
    display name: <yellow>Lucky Box
    lore:
    - <yellow>enthält einen zufälligen Gegenstand.`

**Comment by Cyborax** [comment]
do i need to change something on this script? with version 0.9.8 build(1621) its working without this error.

**Comment by mcmonkey4eva** [comment]
Which build# are you presently running?

**Comment by Cyborax** [comment]
i updated from #1621 to #1625

**Comment by Cyborax** [comment]
ok i tested it now with #1622 and the error occours since this build.

**Comment by mcmonkey4eva** [comment]
Try build DEV-20 http://ci.citizensnpcs.co/job/Denizen_Developmental/20/

**Comment by Cyborax** [comment]
Thank you for this build but its not working.
http://one.denizenscript.com/paste/36435

**Comment by Cyborax** [comment]
Thank you but it's not working for me.
http://one.denizenscript.com/paste/36436

**Comment by mcmonkey4eva** [comment]
Odd. Tried a second time to fix it - could you please test DEV-21 http://ci.citizensnpcs.co/job/Denizen_Developmental/21/ ?

**Comment by Cyborax** [comment]
good job ist working now without errors :)

but now i found the depenizen error in the /denizen debug mode again.
ill post the error to depenizen git

**Comment by mcmonkey4eva** [comment]
Yay! Thanks for the initial report and fix testing!
