### ISSUE TITLE
Error with dezinzen

### ISSUE THREAD

**Issue by kfirsad** [DenizenScript/Denizen-For-Bukkit#1495]
Please help!
just downloaded the plugin for spigot,
and i trying to make an npc sit. 
in the chat its says: 
> java.lang,Nullpointer.Exeption: null

in the console it says: 

```
11.11 02:40:49 [Server] WARN java.lang.NullPointerException
11.11 02:40:49 [Server] WARN at net.aufdemrand.denizen.npc.traits.SittingTrait.sitInternal(SittingTrait.java:85)
11.11 02:40:49 [Server] WARN at net.aufdemrand.denizen.npc.traits.SittingTrait.sit(SittingTrait.java:80)
11.11 02:40:49 [Server] WARN at net.aufdemrand.denizen.NPCCommandHandler.sitting(NPCCommandHandler.java:395)
11.11 02:40:49 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11.11 02:40:49 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11.11 02:40:49 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11.11 02:40:49 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
11.11 02:40:49 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
11.11 02:40:49 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
11.11 02:40:49 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
11.11 02:40:49 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
11.11 02:40:49 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
11.11 02:40:49 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
11.11 02:40:49 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
11.11 02:40:49 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358)
11.11 02:40:49 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193)
11.11 02:40:49 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
11.11 02:40:49 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
11.11 02:40:49 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
11.11 02:40:49 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
11.11 02:40:49 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11.11 02:40:49 [Server] WARN at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
11.11 02:40:49 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
11.11 02:40:49 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
11.11 02:40:49 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
11.11 02:40:49 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
11.11 02:40:49 [Server] WARN at java.lang.Thread.run(Thread.java:745)
```

Thanks in advance!

**Comment by Morphan1** [comment]
Edited for saner stacktrace (it was upside-down before, likely Multicraft or the like)

**Comment by kfirsad** [comment]
someone? please...

**Comment by mcmonkey4eva** [comment]
It might be sitting just got borked by @Morphan1 's random editing of the code base.

We don't really strongly support the sit feature, as it's... never been consistent.

You might be able to `/ex animate <npc> animation:sit` and that'd work?
