### ISSUE TITLE
attack_speed mech returning errors (or I'm just being stupid)

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1498]
I am using the latest Denizen build (#1630) with the same server specs as before (Spigot 1.10). When I try to adjust or set the attack_speed mech for an item, I get a large error debug.

```
[08:46:54] [Server thread/WARN]: java.lang.NullPointerException
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizen.utilities.nbt.CustomNBT.getAttributes(CustomNBT.java:58)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.properties.item.ItemAttributeNBT.getPropertyString(ItemAttributeNBT.java:69)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getPropertiesString(PropertyParser.java:63)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.dItem.identify(dItem.java:525)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.commands.core.AdjustCommand.execute(AdjustCommand.java:106)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:248)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:678)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:509)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:528)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizencore.events.OldEventManager.doEvents(OldEventManager.java:246)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizencore.events.OldEventManager.doEvents(OldEventManager.java:192)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.containers.core.BukkitWorldScriptHelper.doEvents(BukkitWorldScriptHelper.java:55)
[08:46:54] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.containers.core.BukkitWorldScriptHelper.playerInteract(BukkitWorldScriptHelper.java:522)
[08:46:54] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:46:54] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:46:54] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:46:54] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:46:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[08:46:54] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[08:46:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[08:46:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[08:46:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231)
[08:46:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198)
[08:46:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194)
[08:46:54] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:953)
[08:46:54] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
[08:46:54] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[08:46:54] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[08:46:54] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[08:46:54] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[08:46:54] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[08:46:54] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[08:46:54] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[08:46:54] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[08:46:54] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[08:46:54] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```
The script I was using is
```yaml
gold_coin_test:
  type: world
  debug: false
  
  events:
    on player right clicks with gold_coin:
    - adjust <player.item_in_hand> 'attack_speed:<player.item_in_hand.attack_speed.include[<util.random.uuid>/DHI1/add_number/2]||li@<util.random.uuid>/DHI1/add_number/2>' save:testItem
    - take slot:<player.item_in_hand.slot>
    - give <entry[testItem].result>
```
The previous version was just this:
```yaml
gold_coin_test:
  type: world
  debug: false
  
  events:
    on player right clicks with gold_coin:
    - adjust <player.item_in_hand> 'attack_speed:<util.random.uuid>/DHI1/add_number/2>' save:testItem
    - take slot:<player.item_in_hand.slot>
    - give <entry[testItem].result>
```
Neither worked and returned the errors.

**Comment by mcmonkey4eva** [comment]
Try using latest build of Denizen with `nbt_attributes` mech instead of `attack_speed`

**Comment by mcmonkey4eva** [comment]
Oh also, your second one makes a lot more sense but has a typo of a `>` after the 2 that doesn't belong.

**Comment by MusicScore** [comment]
Updated the script to:
```yaml
gold_coin_test:
  type: world
  debug: false
  
  events:
    on player right clicks with gold_coin:
    - adjust <player.item_in_hand> 'nbt_attributes:generic.attackSpeed/mainhand/0/10' save:testItem
    - take slot:<player.item_in_hand.slot>
    - give <entry[testItem].result>
```
Still got an error.
```
[09:02:35] [Server thread/WARN]: java.lang.ClassCastException: java.util.Collections$UnmodifiableRandomAccessList cannot be cast to net.aufdemrand.denizen.nms.util.jnbt.CompoundTag
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizen.utilities.nbt.CustomNBT.addAttribute(CustomNBT.java:104)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.properties.item.ItemAttributeNBT.adjust(ItemAttributeNBT.java:106)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.dItem.adjust(dItem.java:1083)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.dItem.applyProperty(dItem.java:1075)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.ObjectFetcher.getObjectFrom(ObjectFetcher.java:164)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.dList.filter(dList.java:236)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.commands.item.GiveCommand.parseArgs(GiveCommand.java:61)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:220)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:678)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:509)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:528)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizencore.events.OldEventManager.doEvents(OldEventManager.java:246)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizencore.events.OldEventManager.doEvents(OldEventManager.java:192)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.containers.core.BukkitWorldScriptHelper.doEvents(BukkitWorldScriptHelper.java:55)
[09:02:35] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.containers.core.BukkitWorldScriptHelper.playerInteract(BukkitWorldScriptHelper.java:522)
[09:02:35] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:02:35] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:02:35] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:02:35] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[09:02:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[09:02:35] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[09:02:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[09:02:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[09:02:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231)
[09:02:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198)
[09:02:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194)
[09:02:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:953)
[09:02:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
[09:02:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[09:02:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[09:02:35] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[09:02:35] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[09:02:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[09:02:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[09:02:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[09:02:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[09:02:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[09:02:35] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by MusicScore** [comment]
Thank you @mcmonkey4eva for resolving this with the **Denizen_Developmental #60 build**!
