### ISSUE TITLE
Error booting up server 

### ISSUE THREAD

**Issue by KiwiClipClop** [DenizenScript/Denizen-For-Bukkit#1501]
[12:29:39] [Server thread/INFO]: [Denizen] Enabling Denizen v1.0.0-SNAPSHOT (build 1626)
[12:29:39] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mInitializing Denizen Core v1.15 (Build 74), 
                   implementation for Bukkit version 1.0.0-SNAPSHOT (build 
                   1626) [m
[12:29:39] [Server thread/ERROR]: Error occurred while enabling Denizen v1.0.0-SNAPSHOT (build 1626) (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/Citizens
	at net.aufdemrand.denizen.utilities.depends.Depends.setupCitizens(Depends.java:90) ~[?:?]
	at net.aufdemrand.denizen.utilities.depends.Depends.initialize(Depends.java:26) ~[?:?]
	at net.aufdemrand.denizen.Denizen.onEnable(Denizen.java:389) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.Citizens
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
	... 14 more
[12:29:39] [Server thread/INFO]: [XPboost] Enabling XPboost v1.78
[12:29:39] [Server thread/INFO]: [XPboost] Disabled due to no Vault dependency found!

**Comment by mcmonkey4eva** [comment]
Can you try the latest build from http://ci.citizensnpcs.co/job/Denizen/ ?
