### ISSUE TITLE
Errors on booting up

### ISSUE THREAD

**Issue by hypersmc** [DenizenScript/Denizen-For-Bukkit#1502]
[04:13:55 INFO]: [Denizen] Enabling Denizen v1.0.1-SNAPSHOT (build 1630)
[04:13:55 INFO]: +> [Denizen] Initializing Denizen Core v1.15 (Build 77), 
                   implementation for Bukkit version 1.0.1-SNAPSHOT (build 
                   1630) 
[04:13:55 ERROR]: Error occurred while enabling Denizen v1.0.1-SNAPSHOT (build 1630) (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/Citizens
	at net.aufdemrand.denizen.utilities.depends.Depends.setupCitizens(Depends.java:90) ~[?:?]
	at net.aufdemrand.denizen.utilities.depends.Depends.initialize(Depends.java:26) ~[?:?]
	at net.aufdemrand.denizen.Denizen.onEnable(Denizen.java:392) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[server.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:373) [server.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [server.jar:git-Spigot-d60de0a-a951a88]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.Citizens
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-d60de0a-a951a88]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	... 14 more

AND Yes i have citizens on my server.

**Comment by mcmonkey4eva** [comment]
Can you please pastebin a full startup log? (IE, it should show everything from from the very list line of minecraft logs, til where it wraps up the load sequence, including all of Denizen stuff and Citizens and etc. loading)

**Comment by hypersmc** [comment]
here
http://hastebin.com/jehipiwixu.md

**Comment by mcmonkey4eva** [comment]
@hypersmc Citizens was included twice but didn't load either time.
`[04:13:29] [Server thread/ERROR]: Ambiguous plugin name `Citizens' for files `plugins/citizens-2.0.20-SNAPSHOT.jar' and `plugins/Citizens.jar' in `plugins'`

**Comment by hypersmc** [comment]
[05:50:21 INFO]: HypersMC issued server command: /denizen
[05:50:21 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'denizen' in plugin Denizen v1.0.1-SNAPSHOT (build 1630)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-d60de0a-a951a88]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [server.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [server.jar:git-Spigot-d60de0a-a951a88]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1242) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-d60de0a-a951a88]
	... 15 more

**Comment by mcmonkey4eva** [comment]
... Did you fix the error I mentioned, the two citizens jar files?
