### ISSUE TITLE
NullPointerException for take command

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1506]
Using the latest Denizen_Development version. ```take``` command always returns NullPointerException.

```
[16:17:36] [Server thread/WARN]: java.lang.NullPointerException
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizen.utilities.nbt.CustomNBT.getAttributes(CustomNBT.java:58)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.properties.item.ItemAttributeNBT.getPropertyString(ItemAttributeNBT.java:69)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getPropertiesString(PropertyParser.java:63)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.dItem.getFullString(dItem.java:621)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.dInventory.removeItem(dInventory.java:440)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.commands.item.TakeCommand.execute(TakeCommand.java:181)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:248)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:678)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:509)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:528)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizencore.events.OldEventManager.doEvents(OldEventManager.java:246)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizencore.events.OldEventManager.doEvents(OldEventManager.java:192)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.containers.core.BukkitWorldScriptHelper.doEvents(BukkitWorldScriptHelper.java:55)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizen.events.core.CuboidEnterExitSmartEvent.Fire(CuboidEnterExitSmartEvent.java:243)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizen.events.core.CuboidEnterExitSmartEvent.internalRun(CuboidEnterExitSmartEvent.java:205)
[16:17:36] [Server thread/WARN]: 	at net.aufdemrand.denizen.events.core.CuboidEnterExitSmartEvent.playerMoveEvent(CuboidEnterExitSmartEvent.java:163)
[16:17:36] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
[16:17:36] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:17:36] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:17:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[16:17:36] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:17:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:17:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:17:36] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610)
[16:17:36] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126)
[16:17:36] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[16:17:36] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[16:17:36] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:17:36] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:17:36] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[16:17:36] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[16:17:36] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[16:17:36] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[16:17:36] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[16:17:36] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:17:36] [Server thread/INFO]: +> [Denizen] (Attempted: TAKE "%value%" 
                   "from:<player.inventory>") 
```

Relevant script here:
```yaml
townhall_library:
  type: world
  debug: false
  
  events:
    on player right clicks ITEM_FRAME in spawn_townhall_library_cuboid:
    - if <context.location> == l@458.96875,80.5,-554.5,0.0,90.0,world && <player.flag[item_frame_editing]||null> == null
    {
      - determine passively cancelled
      - if <player.flag[townhall_library_archives]||null> == null
      {
        - flag <player> townhall_library_archives
        - execute as_op "minecraft:give <player.name> written_book 1 0 {display:{Lore:[0:<&dq><&dq>,1:<&dq><&7>Equadox Library Book<&dq>]},pages:[<&dq>[<&bs><&dq><&bs><&dq>,{<&bs><&dq>text<&bs><&dq>:<&bs><&dq>      <&bs><&dq>},{<&bs><&dq>text<&bs><&dq>:<&bs><&dq>The Archives<&bs><&dq>,<&bs><&dq>underlined<&bs><&dq>:true},{<&bs><&dq>text<&bs><&dq>:<&bs><&dq>                                                                All of the old (and new) information can be found by clicking the following link:                                                                                              <&bs><&dq>,<&bs><&dq>color<&bs><&dq>:<&bs><&dq>black<&bs><&dq>,<&bs><&dq>underlined<&bs><&dq>:false},{<&bs><&dq>text<&bs><&dq>:<&bs><&dq><&4><&l>Warning! <&c>No link!<&bs><&dq>,<&bs><&dq>color<&bs><&dq>:<&bs><&dq>black<&bs><&dq>,<&bs><&dq>underlined<&bs><&dq>:false,<&bs><&dq>clickEvent<&bs><&dq>:{<&bs><&dq>action<&bs><&dq>:<&bs><&dq>open_url<&bs><&dq>,<&bs><&dq>value<&bs><&dq>:<&bs><&dq>http://www.equadox.net/<&bs><&dq>},<&bs><&dq>hoverEvent<&bs><&dq>:{<&bs><&dq>action<&bs><&dq>:<&bs><&dq>show_item<&bs><&dq>,<&bs><&dq>value<&bs><&dq>:<&bs><&dq>{id:minecraft:stone,tag:{display:{Name:<&bs><&bs><&bs><&dq><&f>Sorry!<&bs><&bs><&bs><&dq>,Lore:[0:<&bs><&bs><&bs><&dq><&7>The Archives are not ready!<&bs><&bs><&bs><&dq>]}}}<&bs><&dq>}}]<&dq>],title:<&dq>The Archives<&dq>,author:<&dq>the Librarian<&dq>}" silent
      }
    }
    
    on player drops written_book in spawn_townhall_library_cuboid:
    - if '<context.item.lore.contains[<&7>Equadox Library Book]>'
    {
      - adjust <context.entity> pickup_delay:0
    }
    
    on player exits spawn_townhall_library_cuboid:
    - if <player.flag[npc0_borrow_book]||null> != null && <player.flag[npc0_daydream_queue]||null> == 0
    {
      - queue <player.flag[npc0_daydream_queue]> clear
      - flag <player> npc0_borrow_book:!
      - flag <player> npc0_daydream_queue:!
      - narrate "<&f>The Husk goes back to daydreaming."
    }
    - if <player.inventory.contains.material[written_book]>
    {
      - foreach '<player.inventory.list_contents.with_lore[Equadox Library book]>'
      {
        - narrate <def[value]>
        - take %value% from:<player.inventory>
      }
      - narrate 'All of the books you borrowed somehow returned to the library.'
    }
    - flag <player> npc0_borrow_book:!
    - flag <player> npc0_daydream_queue:!
    - flag <player> townhall_library_archives:!
```

**Comment by MusicScore** [comment]
This may have something to do with other plugins which edit NBT directly, such as OldCombatMechanics. Unsure at the moment.

**Comment by mcmonkey4eva** [comment]
Can you open up the player file in NBTEdit or the like, and look at the NBT values? Perhaps send a copy of the file or a screenshot of the NBTEdit item area.

It looks like you have a misformatted item attribute.

**Comment by MusicScore** [comment]
The issue seems to have resolved itself when I completely reset the world. It may have to do with other plugins editing the playerdata files.
