### ISSUE TITLE
Error on server startup?

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1532]
I was using build 123 of the Denizen Developmental plugin, and this error was thrown when I started the server, even though it never appeared before.
```
[21:45:16] [Thread-15/INFO]: ERROR! Internal exception was thrown! 
[21:45:16] [Thread-15/WARN]: java.io.IOException: Server returned HTTP response code: 500 for URL: http://neo.mcmonkey.org/plugins/public_stats?plugin=Denizen&version=1.0.1-SNAPSHOT+%28build+123%29
[21:45:16] [Thread-15/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[21:45:16] [Thread-15/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[21:45:16] [Thread-15/WARN]: 	at net.aufdemrand.denizen.utilities.debugging.StatsRecord.run(StatsRecord.java:39)
```
I just downloaded build 124, and a near identical error popped up.
```
[21:51:40] [Thread-14/INFO]: ERROR! Internal exception was thrown!
[21:51:40] [Thread-14/WARN]: java.io.IOException: Server returned HTTP response code: 500 for URL: http://neo.mcmonkey.org/plugins/public_stats?plugin=Denizen&version=1.0.1-SNAPSHOT+%28build+124%29
[21:51:40] [Thread-14/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[21:51:40] [Thread-14/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[21:51:40] [Thread-14/WARN]: 	at net.aufdemrand.denizen.utilities.debugging.StatsRecord.run(StatsRecord.java:39)
```
<br>I'm unsure of what this means, and if it should concern me at all.

**Comment by mcmonkey4eva** [comment]
Sorry about that, our statistics page was borking. (The service that let's use anonymously count how many servers run Denizen)
Should be not happening any further.

**Comment by MusicScore** [comment]
Alright, thank you for the reassurance!
