### ISSUE TITLE
"fake_equipment" mechanism slightly borked?

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1585]
I used Denizen Developmental build 155, with Spigot 1.8.8

When I run the `fake_equipment` mechanism regularly, it seems to work fine. However, when I try to remove the fake equipment via `adjust <player> fake_equipment:<entity>`, the server returns an ArrayIndexOutOfBoundsException error.

```
[19:33:22] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[19:33:22] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.dPlayer.adjust(dPlayer.java:2752)
[19:33:22] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.commands.core.AdjustCommand.execute(AdjustCommand.java:100)
[19:33:22] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:252)
[19:33:22] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[19:33:22] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:678)
[19:33:22] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[19:33:22] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:509)
[19:33:22] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:528)
[19:33:22] [Server thread/WARN]: 	at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1236)
[19:33:22] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:33:22] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[19:33:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[19:33:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[19:33:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[19:33:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:33:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[19:33:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[19:33:22] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:33:22] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[19:33:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[19:33:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[19:33:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[19:33:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[19:33:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[19:33:22] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by mcmonkey4eva** [comment]
Pushed a fix, try build DEV-157 or higher.

**Comment by MusicScore** [comment]
It appears to work without an issue now. Many thanks!
