### ISSUE TITLE
command error 

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1588]
mc 1.8.9

my script

https://one.denizenscript.com/paste/41839

[18:13:45] [Server thread/INFO]: [0;35;1m [0;31;1mERROR! [0;37;1mWoah! No scripts in /plugins/Denizen/scripts/ to load! [m
[18:13:45] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mScanning 0 world scripts... [m
[18:13:45] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mReloading script events... [m
[18:13:45] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mUpdating saves from v1 to v2... [m
[18:13:45] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mDone! [m
[18:13:45] [Server thread/INFO]: [0;33;1m+> [] [0;37;1m[0;35;1m+-------------------------+ [m
[18:18:12] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mProcessing outside scripts... [m
[18:18:12] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mProcessing unnamed script... [m
[18:18:12] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mProcessing '/whitelist.yml'... [m
[18:18:12] [Server thread/INFO]: [0;35;1m [0;32;1mOKAY! [0;37;1mAll scripts loaded! [m
[18:18:12] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mAdding script WHITELIST_HANDLER as type WORLD [m
[18:18:12] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mAdding script BUILTIN_LOAD_TESTER as type COMMAND [m
[18:18:12] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mAdding script WHITELIST_VERSION as type VERSION [m
[18:18:12] [Server thread/INFO]: [0;33;1m+> [Denizen] [0;37;1mAdding script WHITELIST_COMMAND as type COMMAND [m
[18:18:12] [Server thread/INFO]: [0;35;1m [0;31;1mERROR! [0;37;1mInternal exception was thrown! [m
[18:18:12] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[18:18:12] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:18:12] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:18:12] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:18:12] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.ScriptRegistry._buildCoreYamlScriptContainers(ScriptRegistry.java:79)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizen.Denizen.buildCoreContainers(Denizen.java:1349)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizencore.scripts.ScriptHelper.reloadScripts(ScriptHelper.java:38)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizencore.DenizenCore.loadScripts(DenizenCore.java:105)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizencore.DenizenCore.reloadScripts(DenizenCore.java:121)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizen.DenizenCommandHandler.reload(DenizenCommandHandler.java:440)
[18:18:12] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:18:12] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:18:12] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:18:12] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizen.utilities.command.CommandManager.executeMethod(CommandManager.java:140)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizen.utilities.command.CommandManager.execute(CommandManager.java:66)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizen.utilities.command.CommandManager.executeSafe(CommandManager.java:168)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1246)
[18:18:12] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:18:12] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[18:18:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[18:18:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629)
[18:18:12] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:419)
[18:18:12] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:382)
[18:18:12] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:732)
[18:18:12] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:635)
[18:18:12] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:18:12] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizencore.utilities.CoreUtilities.toLowerCase(CoreUtilities.java:102)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.containers.core.CommandScriptContainer.getCommandName(CommandScriptContainer.java:121)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizen.utilities.DenizenCommand.<init>(DenizenCommand.java:28)
[18:18:12] [Server thread/WARN]: 	at net.aufdemrand.denizen.scripts.containers.core.CommandScriptContainer.<init>(CommandScriptContainer.java:117)
[18:18:12] [Server thread/WARN]: 	... 27 more

**Comment by mcmonkey4eva** [comment]
Can't have a command script without a name!

**Comment by wolfwork** [comment]
I am ashamed of my mistakes
