### ISSUE TITLE
break command throws NPE

### ISSUE THREAD

**Issue by F1shb0ne** [DenizenScript/Denizen-For-Bukkit#1595]
```
[09:20:25 INFO]: Fish issued server command: /ex break <player.location.cursor_on> <n@Jibbers>
[09:20:25 INFO]:  Starting InstantQueue
                   'EXCOMMAND_VerzeichnisOutstandingEligible'...
[09:20:25 INFO]:  Queue 'EXCOMMAND_VerzeichnisOutstandingEligible' Executing:
                   BREAK "<player.location.cursor_on>" "<n@Jibbers>"
[09:20:25 INFO]: +- Executing dCommand: BREAK/p@Fish ---------+
[09:20:25 INFO]:  Filled tag <player.location.cursor_on> with
                   'l@239.0,64.0,33.0,world'.
[09:20:25 INFO]:  Filled tag <n@Jibbers> with 'n@1'.
[09:20:25 INFO]:  ERROR! Woah!! An exception has been called with this command!
[09:20:25 INFO]:  ERROR! Internal exception was thrown!
[09:20:25 WARN]: java.lang.NullPointerException
[09:20:25 WARN]:        at net.aufdemrand.denizen.scripts.commands.npc.BreakCommand.execute(BreakCommand.java:92)
[09:20:25 WARN]:        at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:252)
[09:20:25 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
[09:20:25 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:678)
[09:20:25 WARN]:        at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[09:20:25 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:509)
[09:20:25 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:528)
[09:20:25 WARN]:        at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1236)
[09:20:25 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[09:20:25 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[09:20:25 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[09:20:25 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354)
[09:20:25 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189)
[09:20:25 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[09:20:25 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[09:20:25 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[09:20:25 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:20:25 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:20:25 WARN]:        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[09:20:25 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[09:20:25 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[09:20:25 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[09:20:25 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[09:20:25 WARN]:        at java.lang.Thread.run(Thread.java:748)
[09:20:25 INFO]: +> [Denizen] (Attempted: BREAK "<player.location.cursor_on>"
                   "<n@Jibbers>")
[09:20:25 INFO]: +---------------------+
[09:20:25 INFO]:  Completing queue 'EXCOMMAND_VerzeichnisOutstandingEligible'
                   in 6ms.
```

**Comment by mcmonkey4eva** [comment]
Looks like somebody ( @Morphan1 ?) wanted to upgrade the break command to work with non-NPC entities... and so they changed one variable and wandered off????
