### ISSUE TITLE
skyblock level tag 

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1597]
[23:21:39 INFO]:  ERROR! Internal exception was thrown!
[23:21:39 WARN]: java.lang.reflect.InvocationTargetException
[23:21:39 WARN]:        at sun.reflect.GeneratedMethodAccessor180.invoke(Unknown Source)
[23:21:39 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:21:39 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[23:21:39 WARN]:        at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:87)
[23:21:39 WARN]:        at net.aufdemrand.denizen.objects.dPlayer.getAttribute(dPlayer.java:2159)
[23:21:39 WARN]:        at net.aufdemrand.denizen.tags.core.PlayerTags.playerTags(PlayerTags.java:90)
[23:21:39 WARN]:        at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
[23:21:39 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:21:39 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[23:21:39 WARN]:        at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:83)
[23:21:39 WARN]:        at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:258)
[23:21:39 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:21:39 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:21:39 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[23:21:39 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[23:21:39 WARN]:        at java.lang.Thread.run(Thread.java:748)
[23:21:39 WARN]: Caused by: java.lang.NullPointerException

I'm used <player.skyblock.level||0>

**Comment by mcmonkey4eva** [comment]
Depenizen fault - https://github.com/DenizenScript/Depenizen
Try to record the error more carefully before reposting there, as that error messages is incomplete
