### ISSUE TITLE
IllegalStateException on shutdown

### ISSUE THREAD

**Issue by SlimeDog** [DenizenScript/Denizen-For-Bukkit#1600]
BUG
Spigot 1.12 latest
Citizens 2.0.22-SNAPSHOT (build 1480)
Denizen 1.0.2-SNAPSHOT (build 1638)

> [07:53:45 ERROR]: Exception stopping the server
java.lang.IllegalStateException: no implementation set
        at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:65) ~[?:?]
        at net.citizensnpcs.api.CitizensAPI.getNPCRegistry(CitizensAPI.java:96) ~[?:?]
        at net.aufdemrand.denizen.objects.dEntity.isCitizensNPC(dEntity.java:75) ~[?:?]
        at net.aufdemrand.denizen.objects.dEntity.<init>(dEntity.java:335) ~[?:?]
        at net.aufdemrand.denizen.scripts.containers.core.EntityScriptHelper.unlinkEntity(EntityScriptHelper.java:154) ~[?:?]
        at net.aufdemrand.denizen.utilities.world.DenizenWorldAccess.despawn(DenizenWorldAccess.java:39) ~[?:?]
        at net.aufdemrand.denizen.nms.helpers.WorldHelper_v1_12_R1$1.b(WorldHelper_v1_12_R1.java:70) ~[?:?]
        at net.minecraft.server.v1_12_R1.World.c(World.java:1101) ~[spigot-1.12.jar-2017-06-12-0712:git-Spigot-cd6ba67-2a2d6d6]
        at net.minecraft.server.v1_12_R1.WorldServer.c(WorldServer.java:1179) ~[spigot-1.12.jar-2017-06-12-0712:git-Spigot-cd6ba67-2a2d6d6]
        at net.minecraft.server.v1_12_R1.World.kill(World.java:1137) ~[spigot-1.12.jar-2017-06-12-0712:git-Spigot-cd6ba67-2a2d6d6]
        at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:421) ~[spigot-1.12.jar-2017-06-12-0712:git-Spigot-cd6ba67-2a2d6d6]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1095) ~[spigot-1.12.jar-2017-06-12-0712:git-Spigot-cd6ba67-2a2d6d6]
        at net.minecraft.server.v1_12_R1.PlayerConnection.disconnect(PlayerConnection.java:253) ~[spigot-1.12.jar-2017-06-12-0712:git-Spigot-cd6ba67-2a2d6d6]
        at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_12_R1.disconnect(AbstractListenerPlayIn_v1_12_R1.java:46) ~[?:?]
        at net.minecraft.server.v1_12_R1.PlayerList.u(PlayerList.java:1319) ~[spigot-1.12.jar-2017-06-12-0712:git-Spigot-cd6ba67-2a2d6d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:474) ~[spigot-1.12.jar-2017-06-12-0712:git-Spigot-cd6ba67-2a2d6d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot-1.12.jar-2017-06-12-0712:git-Spigot-cd6ba67-2a2d6d6]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by SlimeDog** [comment]
Haven't noticed the error recently, with Denizen 1.0.2-b195. Thanks.
