### ISSUE TITLE
Getting an Error on launch

### ISSUE THREAD

**Issue by FluffyWolfPanda** [DenizenScript/Denizen-For-Bukkit#1601]
[23:31:56] [Server thread/INFO]: Starting minecraft server version 1.11.2
[23:31:56] [Server thread/INFO]: Loading properties
[23:31:56] [Server thread/INFO]: Default game type: SURVIVAL
[23:31:56] [Server thread/INFO]: Generating keypair
[23:31:56] [Server thread/INFO]: Starting Minecraft server on *:25565
[23:31:56] [Server thread/INFO]: Using default channel type
[23:31:56] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
[23:31:57] [Server thread/INFO]: [Denizen] Loading Denizen v1.0.2-SNAPSHOT (build 1638)
[23:31:57] [Server thread/INFO]: Preparing level "world"
[23:31:57] [Server thread/INFO]: Preparing start region for level 0 (Seed: -4263635781250687022)
[23:31:58] [Server thread/INFO]: Preparing spawn area: 11%
[23:31:59] [Server thread/INFO]: Preparing spawn area: 97%
[23:31:59] [Server thread/INFO]: Preparing start region for level 1 (Seed: -4263635781250687022)
[23:32:00] [Server thread/INFO]: Preparing spawn area: 94%
[23:32:00] [Server thread/INFO]: Preparing start region for level 2 (Seed: -4263635781250687022)
[23:32:00] [Server thread/INFO]: [Denizen] Enabling Denizen v1.0.2-SNAPSHOT (build 1638)
[23:32:00] [Server thread/ERROR]: Error occurred while enabling Denizen v1.0.2-SNAPSHOT (build 1638) (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at net.aufdemrand.denizen.nms.Handler_v1_11_R1.<init>(Handler_v1_11_R1.java:45) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_131]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_131]
	at net.aufdemrand.denizen.nms.NMSHandler.initialize(NMSHandler.java:44) ~[?:?]
	at net.aufdemrand.denizen.Denizen.onEnable(Denizen.java:370) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[craftbukkit.jar:git-Bukkit-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:244) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Bukkit-6e3cec8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-6e3cec8]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	... 19 more
[23:32:01] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:32:01] [Server thread/INFO]: Done (3.867s)! For help, type "help" or "?"

This is the error I'm getting when I launch my server. Any ideas on what would be causing this cause I can't seem to figure it out. I even tried an older version and still go the same exact error.

**Comment by mcmonkey4eva** [comment]
Run SPIGOT not CraftBukkit.
