### ISSUE TITLE
<context.entity> tag

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1607]
denizen build 190
mc 1.8
    on player right clicks player:
      - narrate <context.entity>

[13:47:50 INFO]:  ERROR! Internal exception was thrown!
[13:47:50 WARN]: java.lang.reflect.InvocationTargetException
[13:47:50 WARN]:        at sun.reflect.GeneratedMethodAccessor352.invoke(Unknown Source)
[13:47:50 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:47:50 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[13:47:50 WARN]:        at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:87)
[13:47:50 WARN]:        at net.aufdemrand.denizen.objects.dPlayer.getAttribute(dPlayer.java:2159)
[13:47:50 WARN]:        at net.aufdemrand.denizencore.tags.core.ContextTags.contextTags(ContextTags.java:35)
[13:47:50 WARN]:        at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
[13:47:50 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:47:50 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[13:47:50 WARN]:        at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:83)
[13:47:50 WARN]:        at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:258)
[13:47:50 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:47:50 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[13:47:50 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:47:50 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:47:50 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:47:50 WARN]: Caused by: java.lang.NullPointerException
[13:47:50 WARN]:        at com.wasteofplastic.askyblock.ASkyBlockAPI.getIslandOwnedBy(ASkyBlockAPI.java:416)
[13:47:50 WARN]:        at com.denizenscript.depenizen.bukkit.extensions.askyblock.ASkyBlockPlayerExtension.<init>(ASkyBlockPlayerExtension.java:32)
[13:47:50 WARN]:        at com.denizenscript.depenizen.bukkit.extensions.askyblock.ASkyBlockPlayerExtension.getFrom(ASkyBlockPlayerExtension.java:26)
[13:47:50 WARN]:        ... 16 more
[13:47:50 INFO]:  Filled tag <context.entity> with

**Comment by mcmonkey4eva** [comment]
Issue with Depenizen; https://github.com/DenizenScript/Depenizen
and plugin ASkyBlock.
