### ISSUE TITLE
ANVIL inventory type 

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1610]
MINE_REINFORCE:
  type: inventory
  inventory: ANVIL
  title: ANvil

[16:55:01 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_131]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.server.v1_8_R3.Container.getSlot(Container.java:109) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1463) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        ... 5 more

**Comment by mcmonkey4eva** [comment]
I... don't think that can reasonably be used as an inventory script?
Anvils don't really work the same as most other inventory types...

**Comment by wolfwork** [comment]
would like to use it as a design, but unlike other things, clicking on it causes an error

**Comment by Morphan1** [comment]
Sorry, I don't think this is a reasonable thing to accomplish at the moment.
