### ISSUE TITLE
Error on disable plugin

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Denizen-For-Bukkit#1620]
Hello,

When i stop my server (spigot 1.12 latest), i got this: 
```
[20:28:00] [Server thread/INFO]: [Denizen] Disabling Denizen v1.0.2-SNAPSHOT (build 1638)
[20:28:00] [Server thread/ERROR]: Error occurred while disabling Denizen v1.0.2-SNAPSHOT (build 1638) (Is it up to date?)
java.lang.NullPointerException: null
	at net.aufdemrand.denizen.Denizen.onDisable(Denizen.java:965) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Spigot-7228328-14b597f]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot.jar:git-Spigot-7228328-14b597f]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [spigot.jar:git-Spigot-7228328-14b597f]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:414) [spigot.jar:git-Spigot-7228328-14b597f]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:346) [spigot.jar:git-Spigot-7228328-14b597f]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot.jar:git-Spigot-7228328-14b597f]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot.jar:git-Spigot-7228328-14b597f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
```

thanks

**Comment by mcmonkey4eva** [comment]
Run the dev builds, not the mainline builds, for better 1.12 support. http://ci.citizensnpcs.co/job/Denizen_Developmental/
