### ISSUE TITLE
Could not pass event ProjectileHitEvent

### ISSUE THREAD

**Issue by TheOneTwelfth** [DenizenScript/Denizen-For-Bukkit#1639]
```
Could not pass event ProjectileHitEvent to Denizen v1.0.2-SNAPSHOT (build 1639)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:760) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityArrow.t_(EntityArrow.java:224) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.ProjectileHitEvent.getHitBlock()Lorg/bukkit/block/Block;
	at net.aufdemrand.denizen.events.entity.ProjectileHitsScriptEvent.onProjectileHits(ProjectileHitsScriptEvent.java:170) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	... 14 more
```

This happens at latest Denizen version with Spigot 1.8.8 when someone shoots an arrow.

**Comment by mcmonkey4eva** [comment]
Should be fixed in latest dev build?
