### ISSUE TITLE
Error Enabling Denizen v1.0.2-SNAPSHOT (build 1641) on 1.12.1

### ISSUE THREAD

**Issue by sensorware** [DenizenScript/Denizen-For-Bukkit#1654]
Hello, 

I am getting the following error with the latest plugin and citizens2. 

----------------

[Denizen] Enabling Denizen v1.0.2-SNAPSHOT (build 1641)
[19:12:25 ERROR]: Error occurred while enabling Denizen v1.0.2-SNAPSHOT (build 1641) (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_12_R1/block/CraftBlockEntityState
at net.aufdemrand.denizen.nms.Handler_v1_12_R1.‹init›(Handler_v1_12_R1.java:38) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_45-internal]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_45-internal]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_45-internal]
at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45-internal]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_45-internal]
at net.aufdemrand.denizen.nms.NMSHandler.initialize(NMSHandler.java:44) ~[?:?]
at net.aufdemrand.denizen.Denizen.onEnable(Denizen.java:370) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45-internal]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45-internal]
... 19 more

**Comment by BloodEko** [comment]
Are you using craftbukkit instead of spigot ?

**Comment by sensorware** [comment]
downloaded from here:

https://www.spigotmc.org/resources/denizen.21039/

**Comment by BloodEko** [comment]
Can you give some informations about the serversoftware you use ? ( version , ... )

**Comment by mergu** [comment]
You need to update to the latest 1.12.1 server
