### ISSUE TITLE
UnsupportedOperationException when give item

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Denizen-For-Bukkit#1693]
Hello,

When i do `/ex give Quest_Button_QuestCurrent` with

```
Quest_Button_QuestCurrent:
  type: item
  material: i@book_and_quill
```
i got
```
java.lang.UnsupportedOperationException: Not supported yet.
	at org.bukkit.inventory.meta.ItemMeta$Spigot.isUnbreakable(ItemMeta.java:225)
	at net.aufdemrand.denizen.objects.properties.item.ItemUnbreakable.getPropertyString(ItemUnbreakable.java:54)
	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getPropertiesString(PropertyParser.java:63)
	at net.aufdemrand.denizen.objects.dItem.identify(dItem.java:523)
	at net.aufdemrand.denizen.objects.dItem.toString(dItem.java:624)
	at java.lang.String.valueOf(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at java.util.AbstractCollection.toString(Unknown Source)
	at net.aufdemrand.denizencore.objects.aH.debugObj(aH.java:361)
	at net.aufdemrand.denizen.scripts.commands.item.GiveCommand.execute(GiveCommand.java:128)
	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:252)
	at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:678)
	at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:509)
	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:528)
	at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1252)
```

**Comment by Oruss7** [comment]
I update spigot from 1.12.1 to 1.12.2

**Comment by Oruss7** [comment]
Error only with `i@book_and_quill`...

**Comment by Oruss7** [comment]
Arf, 1.12.2 break the item API ='( 
https://pastebin.com/vj7Mt0wS

**Comment by adexgold** [comment]
I am having this issue also with books, I can use a default book item but if I try to use a book script container it just throws the error when trying to give book to player.

**Comment by Oruss7** [comment]
strange

**Comment by mergu** [comment]
Should be fixed in https://github.com/mcmonkey4eva/Denizen/pull/119
