### ISSUE TITLE
Massive Warning Error in Console

### ISSUE THREAD

**Issue by ZEROOblivious** [DenizenScript/Denizen-For-Bukkit#1698]
Any idea what this warning / error is & how to fix it?

#
29.12 16:59:34 [Server] INFO [Denizen] Enabling Denizen v1.0.2-SNAPSHOT (build 1644)
29.12 16:59:34 [Server] INFO +> [Denizen] Initializing Denizen Core v1.15 (Build 97), 
29.12 16:59:34 [Server] INFO implementation for Bukkit version 1.0.2-SNAPSHOT (build 1644) 
29.12 16:59:34 [Server] INFO +> [Denizen] +-------------------------+ 
29.12 16:59:34 [Server] INFO +> [Denizen] / _ ._ _ _ 
29.12 16:59:34 [Server] INFO +> [Denizen] (/(-/ )/ /_(-/ ) scriptable minecraft 
29.12 16:59:34 [Server] INFO +> [Denizen]
29.12 16:59:34 [Server] INFO +> [Denizen] by: mcmonkey, Morphan1, aufdemrand and others 
29.12 16:59:34 [Server] INFO +> [Denizen] Chat with us at: https://discord.gg/Q6pZGSR 
29.12 16:59:34 [Server] INFO +> [Denizen] Or learn more at: https://denizenscript.com 
29.12 16:59:34 [Server] INFO +> [Denizen] version: 1.0.2-SNAPSHOT (build 1644) 
29.12 16:59:34 [Server] INFO +> [Denizen] +-------------------------+ 
29.12 16:59:34 [Server] WARN java.lang.NullPointerException
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.PacketStatusListener.a(PacketStatusListener.java:124)
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:23)
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:8)
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:126)
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:330)
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:1)
29.12 16:59:34 [Server] WARN at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.12 16:59:34 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.12 16:59:34 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
29.12 16:59:34 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.12 16:59:34 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:275)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.12 16:59:34 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
29.12 16:59:34 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.12 16:59:34 [Server] WARN at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.12 16:59:34 [Server] WARN at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.12 16:59:34 [Server] WARN at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
29.12 16:59:34 [Server] WARN at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
29.12 16:59:34 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
29.12 16:59:34 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
29.12 16:59:34 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
29.12 16:59:34 [Server] WARN at java.lang.Thread.run(Thread.java:748)
29.12 16:59:34 [Server] WARN java.lang.NullPointerException
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.PacketStatusListener.a(PacketStatusListener.java:124)
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:23)
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:8)
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:126)
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:330)
29.12 16:59:34 [Server] WARN at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:1)
29.12 16:59:34 [Server] WARN at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.12 16:59:34 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.12 16:59:34 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.12 16:59:34 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
29.12 16:59:34 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)

**Comment by Morphan1** [comment]
Edited for readability. Are you by chance using `/reload` on your server? Also, try using the latest developmental build: http://ci.citizensnpcs.co/job/Denizen_Developmental/lastSuccessfulBuild/
