### ISSUE TITLE
Denizens wont recognise Citizens

### ISSUE THREAD

**Issue by BearBros** [DenizenScript/Denizen-For-Bukkit#1706]
We took a break for a week and when we came back it was just kind of broke. Can't seem to find the issue. Will post the log below.
I've tried re-downloading them both but nothing seems to work. 

02.01 10:40:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
02.01 10:40:00 [Server] INFO Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
02.01 10:40:00 [Server] INFO in 'string', line 3, column 9:
02.01 10:40:00 [Server] INFO Data: 0
02.01 10:40:00 [Server] INFO ^
02.01 10:40:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
02.01 10:40:01 [Server] INFO Caused by: java.lang.NullPointerException
02.01 10:39:48 [Server] INFO [Denizen] Enabling Denizen v1.0.2-SNAPSHOT (build 1644)
02.01 10:39:48 [Server] INFO +> [Denizen] Initializing Denizen Core v1.15 (Build 97), 
02.01 10:39:48 [Server] INFO implementation for Bukkit version 1.0.2-SNAPSHOT (build 1644) 
02.01 10:39:48 [Server] WARN [Denizen] Citizens does not seem to be activated! Denizen will have greatly reduced functionality!

**Comment by BearBros** [comment]
Solved now. For some reason, world guard is blocking it.
