### ISSUE TITLE
brewing event : <context.inventory.list_contents> throws exception

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1769]
```yaml
test_brewing_system:
  type: world
  debug: true
  events:
    on brewing stand brews:
    - narrate "<context.inventory.list_contents>" targets:<server.list_online_players>
```

```
[15:14:53 INFO]:  Running script event 'Brews', event='brewing stand brews' for script 'ANTIQUIT_SYSTEM' 
[15:14:53 INFO]:  Starting InstantQueue 'TEST_BREWING_SYSTEM_FindsDougDairy'... 
[15:14:53 INFO]:  Queue ''TEST_BREWING_SYSTEM_FindsDougDairy' Executing: NARRATE "<context.inventory.list_contents>" "targets:<server.list_online_players>" 
[15:14:53 INFO]: +- Executing dCommand: NARRATE ---------+ 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Exception trying to fetch color! 
[15:14:53 INFO]:  ERROR! Internal exception was thrown! 
[15:14:53 WARN]: java.lang.reflect.InvocationTargetException
[15:14:53 WARN]: 	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
[15:14:53 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:14:53 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:14:53 WARN]: 	at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:84)
[15:14:53 WARN]: 	at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:262)
[15:14:53 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:14:53 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:14:53 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:14:53 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:14:53 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:14:53 WARN]: Caused by: java.lang.NullPointerException
[15:14:53 WARN]: 	at net.aufdemrand.denizen.objects.dColor.identify(dColor.java:179)
[15:14:53 WARN]: 	at net.aufdemrand.denizen.objects.properties.item.ItemColor.getPropertyString(ItemColor.java:82)
[15:14:53 WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getPropertiesString(PropertyParser.java:63)
[15:14:53 WARN]: 	at net.aufdemrand.denizen.objects.dItem.identify(dItem.java:531)
[15:14:53 WARN]: 	at net.aufdemrand.denizen.objects.properties.inventory.InventoryContents.getContents(InventoryContents.java:55)
[15:14:53 WARN]: 	at net.aufdemrand.denizen.objects.properties.inventory.InventoryContents.getAttribute(InventoryContents.java:199)
[15:14:53 WARN]: 	at net.aufdemrand.denizen.objects.dInventory.getAttribute(dInventory.java:2092)
[15:14:53 WARN]: 	at net.aufdemrand.denizencore.tags.core.ContextTags.contextTags(ContextTags.java:35)
[15:14:53 WARN]: 	... 10 more
[15:14:53 INFO]:  Filled tag <context.inventory.list_contents> with 'context.inventory.list_contents'. 
[15:14:53 INFO]:  ERROR! Tag <context.inventory.list_contents> is invalid! 
[15:14:53 INFO]:  Filled tag <server.list_online_players> with 'li@p@7e76edc9-299d-4556-a485-5879015bebc2'. 
[15:14:53 INFO]: +> Executing 'NARRATE': Narrating='context.inventory.list_contents'  Targets='[p@MrMaleficus]' 
[15:14:53 INFO]:  Completing queue 'TEST_BREWING_SYSTEM_FindsDougDairy' in 7ms. 
```

**Comment by mcmonkey4eva** [comment]
Issue was added in recent dev build by https://github.com/mcmonkey4eva/Denizen/pull/132 
Is fixed in dev-316
