### ISSUE TITLE
NoClassDefFoundError at Shopkeepers/Denizen interface

### ISSUE THREAD

**Issue by SlimeDog** [DenizenScript/Denizen-For-Bukkit#1776]
Spigot 1.12.2 latest
Shopkeepers 2.1.0-beta
Denizen 1.0.2-b322
Citizens 2.0.22-b1547

After a recent Shopkeepers update, the following exception is generated on server restart. I posted  to Shopkeepers first; he believes this is a Denizen issue. Please advise.

```
[18:06:36] [Server thread/WARN]: [Denizen] Task #96 for Denizen v1.0.2-SNAPSHOT (build 322) generated an exception
java.lang.NoClassDefFoundError: com/nisovin/shopkeepers/events/ShopkeeperTradeEvent
        at com.denizenscript.depenizen.bukkit.events.shopkeepers.ShopKeeperTradeScriptEvent.destroy(ShopKeeperTradeScriptEvent.java:73) ~[?:?]
        at net.aufdemrand.denizencore.events.ScriptEvent.reload(ScriptEvent.java:89) ~[?:?]
        at net.aufdemrand.denizencore.DenizenCore.loadScripts(DenizenCore.java:107) ~[?:?]
        at net.aufdemrand.denizen.Denizen$1.run(Denizen.java:912) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: com.nisovin.shopkeepers.events.ShopkeeperTradeEvent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar-2018-06-20-0652:git-Spigot-642f6d2-fbe3046]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
        ... 11 more
```

**Comment by mcmonkey4eva** [comment]
Depenizen issue, report there.
https://github.com/DenizenScript/Depenizen

**Comment by SlimeDog** [comment]
Done: [https://github.com/DenizenScript/Depenizen/issues/205](https://github.com/DenizenScript/Depenizen/issues/205)
