### ISSUE TITLE
"An exception has been called with this command (while preparing it)!"

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1779]
```
[12:35:48 INFO]: +- Building event 'ON PLAYER ENTERS NOTABLE CUBOID' for CUBOID_ENTER_EXIT_EVENT ---------+
[12:35:48 INFO]:  Starting InstantQueue 'CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical'...
[12:35:48 INFO]:  Queue 'CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical' Executing: WAIT "1t"
[12:35:48 INFO]: +- Executing dCommand: WAIT/p@MrMaleficus ---------+
[12:35:48 INFO]: +> Executing 'WAIT': queue='CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical'  delay='d@0.05s'
[12:35:48 INFO]:  Forcing queue CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical into a timed queue...
[12:35:48 INFO]:  Completing queue 'CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical' in 0ms.
[12:35:48 INFO]:  Starting TimedQueue 'CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical'...
[12:35:48 INFO]:  Queue 'CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical' Executing: IF "<yaml.list.contains[<pl.uuid>].not>" "queue" "clear"
[12:35:48 INFO]: +- Executing dCommand: IF/p@MrMaleficus ---------+
[12:35:48 INFO]: +> Executing 'IF': use_braces='false'
[12:35:48 INFO]:  Filled tag <pl.uuid> with '7e76edc9-299d-4556-a485-5879015bebc2'.
[12:35:48 INFO]:  Filled tag <yaml.list.contains[7e76edc9-299d-4556-a485-5879015bebc2].not> with 'false'.
[12:35:48 INFO]:  Queue 'CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical' Executing: DEFINE "chunk_orig" "<context.from.chunk>"
[12:35:48 INFO]: +- Executing dCommand: DEFINE/p@MrMaleficus ---------+
[12:35:48 INFO]:  Filled tag <context.from.chunk> with 'ch@46,-23,GuildesTest'.
[12:35:48 INFO]: +> Executing 'DEFINE': queue='CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical'  definition='chunk_orig'  value='ch@46,-23,GuildesTest'
[12:35:48 INFO]:  Queue 'CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical' Executing: DEFINE "chunk_dest" "<context.to.chunk>"
[12:35:48 INFO]: +- Executing dCommand: DEFINE/p@MrMaleficus ---------+
[12:35:48 INFO]:  Filled tag <context.to.chunk> with 'ch@45,-23,GuildesTest'.
[12:35:48 INFO]: +> Executing 'DEFINE': queue='CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical'  definition='chunk_dest'  value='ch@45,-23,GuildesTest'
[12:35:48 INFO]:  Queue 'CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical' Executing: IF "<yaml[babylone_guildes_index].contains[territoires.%chunk_dest%]>" "{" "-" "if" "<yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>" "=="
                   "<yaml[babylone_guildes_index].read[territoires.%chunk_orig%.guilde]||false>" "queue" "clear" "-" "title"
                   "subtitle:<proc[color_diplo_b_list].context[<player>|<yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>]><yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>" "stay:1s" "-" "if"
                   "<yaml[b_<yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>].contains[general.accueil]>" "narrate" "<&6>~ <&e><yaml[b_<yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>].read[general.accueil]>" "}"
[12:35:48 INFO]: +- Executing dCommand: IF/p@MrMaleficus ---------+
[12:35:48 INFO]:  ERROR in script 'CUBOID_ENTER_EXIT_EVENT'! Woah! An exception has been called with this command (while preparing it)!
[12:35:48 INFO]:  ERROR in script 'CUBOID_ENTER_EXIT_EVENT'! Internal exception was thrown!
[12:35:48 WARN]: java.lang.NullPointerException
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.ScriptEntry.regenerateArgsCur(ScriptEntry.java:98)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:112)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:70)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:662)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue.access$000(TimedQueue.java:12)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue$1.run(TimedQueue.java:163)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.utilities.scheduling.RepeatingSchedulable.tick(RepeatingSchedulable.java:20)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.DenizenCore.tick(DenizenCore.java:155)
[12:35:48 WARN]:        at net.aufdemrand.denizen.Denizen$6.run(Denizen.java:952)
[12:35:48 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[12:35:48 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[12:35:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[12:35:48 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:35:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:35:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:35:48 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:35:48 INFO]: +> [Denizen] (Attempted: IF "<yaml[babylone_guildes_index].contains[territoires.%chunk_dest%]>" "{" "-" "if" "<yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>" "=="
                   "<yaml[babylone_guildes_index].read[territoires.%chunk_orig%.guilde]||false>" "queue" "clear" "-" "title"
                   "subtitle:<proc[color_diplo_b_list].context[<player>|<yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>]><yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>" "stay:1s" "-" "if"
                   "<yaml[b_<yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>].contains[general.accueil]>" "narrate" "<&6>~ <&e><yaml[b_<yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>].read[general.accueil]>" "}")
[12:35:48 INFO]: +---------------------+
[12:35:48 INFO]:  Queue 'CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical' Executing: IF "<yaml[babylone_poi_index].contains[territoires_poi.%chunk_dest%]>" "{" "-" "if" "<yaml[babylone_poi_index].contains[territoires_poi.%chunk_dest%.nom]>" "=="
                   "<yaml[babylone_poi_index].contains[territoires_poi.%chunk_orig%.nom]||false>" "queue" "clear" "-" "define" "poi" "<yaml[babylone_poi_index].read[territoires_poi.%chunk_dest%.nom]>" "-" "if" "<yaml[babylone_poi_index].contains[poi_list.%poi%.guilde]>"
                   "{" "-" "define" "color_diplo" "<proc[color_diplo_b_list].context[<player>|<yaml[babylone_poi_index].read[poi_list.%poi%.guilde]>]>" "}" "else" "{" "-" "define" "color_diplo" "<&f>" "}" "-" "title" "subtitle:<&b>[%color_diplo%POI<&b>]
                   <&e><yaml[babylone_poi_index].read[poi_list.%poi%.nom]> <&b>Niv.<yaml[babylone_poi_index].read[poi_list.%poi%.level]>" "stay:1s" "}"
[12:35:48 INFO]: +- Executing dCommand: IF/p@MrMaleficus ---------+
[12:35:48 INFO]:  ERROR in script 'CUBOID_ENTER_EXIT_EVENT'! Woah! An exception has been called with this command (while preparing it)!
[12:35:48 INFO]:  ERROR in script 'CUBOID_ENTER_EXIT_EVENT'! Internal exception was thrown!
[12:35:48 WARN]: java.lang.NullPointerException
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.ScriptEntry.regenerateArgsCur(ScriptEntry.java:98)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:112)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:70)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:662)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue.access$000(TimedQueue.java:12)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue$1.run(TimedQueue.java:163)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.utilities.scheduling.RepeatingSchedulable.tick(RepeatingSchedulable.java:20)
[12:35:48 WARN]:        at net.aufdemrand.denizencore.DenizenCore.tick(DenizenCore.java:155)
[12:35:48 WARN]:        at net.aufdemrand.denizen.Denizen$6.run(Denizen.java:952)
[12:35:48 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[12:35:48 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[12:35:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[12:35:48 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:35:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:35:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:35:48 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:35:48 INFO]: +> [Denizen] (Attempted: IF "<yaml[babylone_poi_index].contains[territoires_poi.%chunk_dest%]>" "{" "-" "if" "<yaml[babylone_poi_index].contains[territoires_poi.%chunk_dest%.nom]>" "=="
                   "<yaml[babylone_poi_index].contains[territoires_poi.%chunk_orig%.nom]||false>" "queue" "clear" "-" "define" "poi" "<yaml[babylone_poi_index].read[territoires_poi.%chunk_dest%.nom]>" "-" "if" "<yaml[babylone_poi_index].contains[poi_list.%poi%.guilde]>"
                   "{" "-" "define" "color_diplo" "<proc[color_diplo_b_list].context[<player>|<yaml[babylone_poi_index].read[poi_list.%poi%.guilde]>]>" "}" "else" "{" "-" "define" "color_diplo" "<&f>" "}" "-" "title" "subtitle:<&b>[%color_diplo%POI<&b>]
                   <&e><yaml[babylone_poi_index].read[poi_list.%poi%.nom]> <&b>Niv.<yaml[babylone_poi_index].read[poi_list.%poi%.level]>" "stay:1s" "}")
[12:35:48 INFO]: +---------------------+
[12:35:48 INFO]:  Queue 'CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical' Executing: INJECT "sidebar_actu_auto" "instantly"
[12:35:48 INFO]: +- Executing dCommand: INJECT/p@MrMaleficus ---------+
[12:35:48 INFO]: +> Executing 'INJECT': script='SIDEBAR_ACTU_AUTO(TASK)'  instant='true'
[12:35:48 INFO]:  Completing queue 'CUBOID_ENTER_EXIT_EVENT_DigitalMotorcyclesStatistical' in 149ms.
[12:37:13 INFO]: [MythicMobs] Saving all active Mythic Mobs...
[12:37:13 INFO]: [MythicMobs] All active mobs have been saved!
```
```yaml
cuboid_enter_exit_event:
  type: world
  debug: true
  events:
    on player enters notable cuboid:
    - wait 1t
    - if <yaml.list.contains[<pl.uuid>].not> queue clear
    - define chunk_orig <context.from.chunk>
    - define chunk_dest <context.to.chunk>
    - if <yaml[babylone_guildes_index].contains[territoires.%chunk_dest%]> {
      - if <yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]> == <yaml[babylone_guildes_index].read[territoires.%chunk_orig%.guilde]||false> queue clear
      - title 'subtitle:<proc[color_diplo_b_list].context[<player>|<yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>]><yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>' stay:1s
      - if <yaml[b_<yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>].contains[general.accueil]> narrate "<&6>~ <&e><yaml[b_<yaml[babylone_guildes_index].read[territoires.%chunk_dest%.guilde]>].read[general.accueil]>"
    }
    - if <yaml[babylone_poi_index].contains[territoires_poi.%chunk_dest%]> {
      - if <yaml[babylone_poi_index].contains[territoires_poi.%chunk_dest%.nom]> == <yaml[babylone_poi_index].contains[territoires_poi.%chunk_orig%.nom]||false> queue clear
      - define poi <yaml[babylone_poi_index].read[territoires_poi.%chunk_dest%.nom]>
      - if <yaml[babylone_poi_index].contains[poi_list.%poi%.guilde]> {
        - define color_diplo <proc[color_diplo_b_list].context[<player>|<yaml[babylone_poi_index].read[poi_list.%poi%.guilde]>]>
      } else {
        - define color_diplo <&f>
      }
      - title "subtitle:<&b>[%color_diplo%POI<&b>] <&e><yaml[babylone_poi_index].read[poi_list.%poi%.nom]> <&b>Niv.<yaml[babylone_poi_index].read[poi_list.%poi%.level]>" stay:1s
    }
    - inject sidebar_actu_auto instantly
```

Using latest dev with the major rewrites :)
(This script worked perfectly before the massive dCore rewrites :D)

**Comment by mcmonkey4eva** [comment]
fixed in core
