### ISSUE TITLE
dDiscordBot Channel Error

### ISSUE THREAD

**Issue by Elxafil** [DenizenScript/Denizen-For-Bukkit#1792]
Basically I did exactly what the docs said to get the Discord bot to work:
`DiscordHook:
    type: world
    events:
    
        on server starts:
        - inject DiscordConnect
        on reload scripts:
        - discord id:protocol73 disconnect
        - inject DiscordConnect
        
        on player joins:
        - discord id:protocol73 message channel:<discord[Craftico].server[Craftico].channel[protocol73]> "Testing..."`

Which essentially spits out this error:
`[12:47:38 INFO]:  Running script event 'PlayerJoins', event='player joins' for script 'DISCORDHOOK'
[12:47:38 INFO]:  Starting InstantQueue 'DISCORDHOOK_ViolationArrangementThinking'...
[12:47:38 INFO]:  Queue 'DISCORDHOOK_ViolationArrangementThinking' Executing: DISCORD "id:protocol73" "message"
                   "channel:<discord[Craftico].server[Craftico].channel[protocol73]>" "Testing..."
[12:47:38 INFO]: +- Executing dCommand: DISCORD/p@Elxafil ---------+
[12:47:38 INFO]:  Filled tag <discord[Craftico].server[Craftico].channel[protocol73]> with
                   'discord[Craftico].server[Craftico].channel[protocol73]'.
[12:47:38 INFO]:  ERROR! Tag <discord[Craftico].server[Craftico].channel[protocol73]> is invalid!
[12:47:38 INFO]: +> Executing 'DISCORD': id='protocol73'  channel='discord[Craftico].server[Craftico].channel[protocol73]'
                   instruction='message'  message='Testing...'
[12:47:38 INFO]:  ERROR! 'discord[Craftico].server[Craftico].channel[protocol73]' is not a valid integer!
[12:47:38 INFO]:  ERROR! Woah!! An exception has been called with this command (while executing it)!
[12:47:38 INFO]:  ERROR! Internal exception was thrown!
[12:47:38 WARN]: java.lang.NullPointerException
[12:47:38 WARN]:        at com.denizenscript.ddiscordbot.DiscordCommand.execute(DiscordCommand.java:172)
[12:47:38 WARN]:        at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:168)
[12:47:38 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:70)
[12:47:38 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:670)
[12:47:38 WARN]:        at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[12:47:38 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.runMeNow(ScriptQueue.java:465)
[12:47:38 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:516)
[12:47:38 WARN]:        at net.aufdemrand.denizencore.events.ScriptEvent.run(ScriptEvent.java:295)
[12:47:38 WARN]:        at net.aufdemrand.denizencore.events.ScriptEvent.fire(ScriptEvent.java:254)
[12:47:38 WARN]:        at net.aufdemrand.denizen.events.player.PlayerJoinsScriptEvent.onPlayerJoins(PlayerJoinsScriptEvent.java:101)
[12:47:38 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:47:38 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:47:38 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:47:38 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[12:47:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[12:47:38 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:47:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[12:47:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[12:47:38 WARN]:        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346)
[12:47:38 WARN]:        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166)
[12:47:38 WARN]:        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159)
[12:47:38 WARN]:        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57)
[12:47:38 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233)
[12:47:38 WARN]:        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140)
[12:47:38 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845)
[12:47:38 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:47:38 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:47:38 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:47:38 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:47:38 INFO]: +> [Denizen] (Attempted: DISCORD "id:protocol73" "message" "channel:<discord[Craftico].server[Craftico].channel[protocol73]>"
                   "Testing...")
[12:47:38 INFO]: +---------------------+`

**Comment by mcmonkey4eva** [comment]
As mentioned on Discord: tags don't exist yet, use IDs.
Also, dDiscordBot issues are posted on https://github.com/DenizenScript/dDiscordBot
