### ISSUE TITLE
Maps dont work in 1.13

### ISSUE THREAD

**Issue by writeescape** [DenizenScript/Denizen-For-Bukkit#1793]
```
Thu, 26. Jul 2018 17:00:40 BST INFO]  Queue 'EXCOMMAND_DrawingMorrisonAppreciation' Executing: MAP "126" "image:images/photo.png" "resize" 
[Thu, 26. Jul 2018 17:00:40 BST INFO] +- Executing dCommand: MAP/p@WriteEscape ---------+ 
[Thu, 26. Jul 2018 17:00:40 BST INFO] +> Executing 'MAP': map-id='126'  reset='false'  image='images/photo.png'  resize='true'  x-value='0'  y-value='0' 
[Thu, 26. Jul 2018 17:00:40 BST INFO]  Completing queue 'EXCOMMAND_DrawingMorrisonAppreciation' in 5ms. 
[Thu, 26. Jul 2018 17:00:40 BST INFO]  ERROR! Internal exception was thrown! 
[Thu, 26. Jul 2018 17:00:40 BST WARN] java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at java.awt.image.DirectColorModel.createCompatibleWritableRaster(java.desktop@9-internal/DirectColorModel.java:1016)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at java.awt.image.BufferedImage.<init>(java.desktop@9-internal/BufferedImage.java:333)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.aufdemrand.denizen.utilities.maps.MapImage.imageToBytes(MapImage.java:113)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.aufdemrand.denizen.utilities.maps.MapImage.render(MapImage.java:77)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.aufdemrand.denizen.utilities.maps.DenizenMapRenderer.render(DenizenMapRenderer.java:99)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at org.bukkit.craftbukkit.v1_13_R1.map.CraftMapView.render(CraftMapView.java:148)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.minecraft.server.v1_13_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:380)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.minecraft.server.v1_13_R1.WorldMap.a(WorldMap.java:286)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.minecraft.server.v1_13_R1.ItemWorldMap.a(ItemWorldMap.java:329)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.minecraft.server.v1_13_R1.EntityPlayer.playerTick(EntityPlayer.java:375)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.minecraft.server.v1_13R1.PlayerConnection.Y(PlayerConnection.java:138)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_13R1.Y(AbstractListenerPlayIn_v1_13_R1.java:76)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.minecraft.server.v1_13_R1.NetworkManager.a(NetworkManager.java:231)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.minecraft.server.v1_13_R1.ServerConnection.c(ServerConnection.java:120)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:984)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[Thu, 26. Jul 2018 17:00:40 BST WARN]     at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
[Thu, 26. Jul 2018 17:00:40 BST WARN] Failed to handle packet for /82.6.185.126:53518
[Thu, 26. Jul 2018 17:00:40 BST INFO] WriteEscape lost connection: Internal server error
```

**Comment by mcmonkey4eva** [comment]
Bad file path, you want `image:photo.png` without `images/`, as the system starts within `images/`
