### ISSUE TITLE
EventException on add wooden_axe to inventory

### ISSUE THREAD

**Issue by SlimeDog** [DenizenScript/Denizen-For-Bukkit#1798]
Spigot 1.13 latest
Citizens 2.0.23-b1562
Denizen 1.0.3-b400

```
[06:34:32] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to Denizen v1.0.3-SNAPSHOT (build 400)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2288) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalArgumentException: Cannot get data for not block WOODEN_AXE
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at org.bukkit.craftbukkit.v1_13_R1.block.data.CraftBlockData.newData(CraftBlockData.java:464) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createBlockData(CraftServer.java:1808) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createBlockData(CraftServer.java:1783) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1185) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        at net.aufdemrand.denizen.nms.impl.blocks.BlockData_v1_13_R1.<init>(BlockData_v1_13_R1.java:25) ~[?:?]
        at net.aufdemrand.denizen.nms.helpers.BlockHelper_v1_13_R1.getBlockData(BlockHelper_v1_13_R1.java:107) ~[?:?]
        at net.aufdemrand.denizen.objects.dMaterial.getMaterialFrom(dMaterial.java:604) ~[?:?]
        at net.aufdemrand.denizen.objects.dItem.identifyMaterial(dItem.java:566) ~[?:?]
        at net.aufdemrand.denizen.objects.dItem.identifySimple(dItem.java:560) ~[?:?]
        at net.aufdemrand.denizen.scripts.containers.core.BukkitWorldScriptHelper.inventoryClickEvent(BukkitWorldScriptHelper.java:264) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar-2018-08-06-0614:git-Spigot-1503de9-200b239]
        ... 15 more
```

**Comment by mcmonkey4eva** [comment]
Should be fixed in build dev 401

**Comment by SlimeDog** [comment]
Confirmed fixed in dev 401
