### ISSUE TITLE
Error with PlayerDeathEvent.

### ISSUE THREAD

**Issue by Roos1K** [DenizenScript/Denizen-For-Bukkit#1800]
Using: 
Spigot 1.13 latest.
Denizen 1.0.3 build-401.

```
[18:47:47] [Server thread/INFO]:  ERROR! Internal exception was thrown! 
[18:47:47] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[18:47:47] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor204.invoke(Unknown Source)
[18:47:47] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:47:47] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser$1.get(PropertyParser.java:54)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:138)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getPropertiesString(PropertyParser.java:80)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.dItem.identify(dItem.java:534)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.events.entity.EntityDeathScriptEvent.onEntityDeath(EntityDeathScriptEvent.java:273)
[18:47:47] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source)
[18:47:47] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:47:47] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:419)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityPlayer.die(EntityPlayer.java:496)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityLiving.damageEntity(EntityLiving.java:1054)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityHuman.damageEntity(EntityHuman.java:799)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityPlayer.damageEntity(EntityPlayer.java:608)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.Explosion.a(Explosion.java:139)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.createExplosion(World.java:1644)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.WorldServer.createExplosion(WorldServer.java:1054)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.createExplosion(World.java:1634)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityCreeper.dF(EntityCreeper.java:203)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityCreeper.tick(EntityCreeper.java:112)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.entityJoinedWorld(World.java:1360)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.g(World.java:1327)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.tickEntities(World.java:1161)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.WorldServer.tickEntities(WorldServer.java:601)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:956)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[18:47:47] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:47:47] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.load(CraftBanner.java:33)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.load(CraftBanner.java:1)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:39)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.<init>(CraftBanner.java:26)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:373)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.properties.item.ItemInventory.describes(ItemInventory.java:20)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.properties.item.ItemInventory.getFrom(ItemInventory.java:24)
[18:47:47] [Server thread/WARN]: 	... 35 more
[18:47:47] [Server thread/INFO]:  ERROR! Internal exception was thrown! 
[18:47:47] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[18:47:47] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source)
[18:47:47] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:47:47] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser$1.get(PropertyParser.java:54)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:138)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getPropertiesString(PropertyParser.java:80)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.dItem.identify(dItem.java:534)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.events.entity.EntityDeathScriptEvent.onEntityDeath(EntityDeathScriptEvent.java:273)
[18:47:47] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source)
[18:47:47] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:47:47] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:419)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityPlayer.die(EntityPlayer.java:496)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityLiving.damageEntity(EntityLiving.java:1054)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityHuman.damageEntity(EntityHuman.java:799)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityPlayer.damageEntity(EntityPlayer.java:608)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.Explosion.a(Explosion.java:139)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.createExplosion(World.java:1644)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.WorldServer.createExplosion(WorldServer.java:1054)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.createExplosion(World.java:1634)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityCreeper.dF(EntityCreeper.java:203)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityCreeper.tick(EntityCreeper.java:112)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.entityJoinedWorld(World.java:1360)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.g(World.java:1327)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.tickEntities(World.java:1161)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.WorldServer.tickEntities(WorldServer.java:601)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:956)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[18:47:47] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:47:47] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.load(CraftBanner.java:33)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.load(CraftBanner.java:1)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:39)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.<init>(CraftBanner.java:26)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:373)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.properties.item.ItemLock.describes(ItemLock.java:19)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.properties.item.ItemLock.getFrom(ItemLock.java:23)
[18:47:47] [Server thread/WARN]: 	... 35 more
[18:47:47] [Server thread/INFO]:  ERROR! Internal exception was thrown! 
[18:47:47] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[18:47:47] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source)
[18:47:47] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:47:47] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser$1.get(PropertyParser.java:54)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:138)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getPropertiesString(PropertyParser.java:80)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.dItem.identify(dItem.java:534)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.events.entity.EntityDeathScriptEvent.onEntityDeath(EntityDeathScriptEvent.java:273)
[18:47:47] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source)
[18:47:47] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:47:47] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:419)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityPlayer.die(EntityPlayer.java:496)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityLiving.damageEntity(EntityLiving.java:1054)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityHuman.damageEntity(EntityHuman.java:799)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityPlayer.damageEntity(EntityPlayer.java:608)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.Explosion.a(Explosion.java:139)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.createExplosion(World.java:1644)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.WorldServer.createExplosion(WorldServer.java:1054)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.createExplosion(World.java:1634)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityCreeper.dF(EntityCreeper.java:203)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.EntityCreeper.tick(EntityCreeper.java:112)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.entityJoinedWorld(World.java:1360)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.g(World.java:1327)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.World.tickEntities(World.java:1161)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.WorldServer.tickEntities(WorldServer.java:601)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:956)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[18:47:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[18:47:47] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:47:47] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.load(CraftBanner.java:33)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.load(CraftBanner.java:1)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:39)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.<init>(CraftBanner.java:26)
[18:47:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:373)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.properties.item.ItemSignContents.describes(ItemSignContents.java:22)
[18:47:47] [Server thread/WARN]: 	at net.aufdemrand.denizen.objects.properties.item.ItemSignContents.getFrom(ItemSignContents.java:26)
[18:47:47] [Server thread/WARN]: 	... 35 more
[18:47:47] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Denizen v1.0.3-SNAPSHOT (build 401)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[minecraft_server.jar:git-Spigot-1503de9-200b239]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-1503de9-200b239]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:419) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.EntityPlayer.die(EntityPlayer.java:496) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.EntityLiving.damageEntity(EntityLiving.java:1054) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.EntityHuman.damageEntity(EntityHuman.java:799) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.EntityPlayer.damageEntity(EntityPlayer.java:608) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.Explosion.a(Explosion.java:139) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.World.createExplosion(World.java:1644) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.WorldServer.createExplosion(WorldServer.java:1054) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.World.createExplosion(World.java:1634) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.EntityCreeper.dF(EntityCreeper.java:203) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.EntityCreeper.tick(EntityCreeper.java:112) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.World.entityJoinedWorld(World.java:1360) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.World.g(World.java:1327) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.World.tickEntities(World.java:1161) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.WorldServer.tickEntities(WorldServer.java:601) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:956) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [minecraft_server.jar:git-Spigot-1503de9-200b239]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.load(CraftBanner.java:33) ~[minecraft_server.jar:git-Spigot-1503de9-200b239]
	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.load(CraftBanner.java:1) ~[minecraft_server.jar:git-Spigot-1503de9-200b239]
	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:39) ~[minecraft_server.jar:git-Spigot-1503de9-200b239]
	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.<init>(CraftBanner.java:26) ~[minecraft_server.jar:git-Spigot-1503de9-200b239]
	at org.bukkit.craftbukkit.v1_13_R1.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:373) ~[minecraft_server.jar:git-Spigot-1503de9-200b239]
	at net.aufdemrand.denizen.objects.properties.item.ItemBaseColor.getBaseColor(ItemBaseColor.java:48) ~[?:?]
	at net.aufdemrand.denizen.objects.properties.item.ItemBaseColor.getPropertyString(ItemBaseColor.java:100) ~[?:?]
	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getPropertiesString(PropertyParser.java:81) ~[?:?]
	at net.aufdemrand.denizen.objects.dItem.identify(dItem.java:534) ~[?:?]
	at net.aufdemrand.denizen.events.entity.EntityDeathScriptEvent.onEntityDeath(EntityDeathScriptEvent.java:273) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[minecraft_server.jar:git-Spigot-1503de9-200b239]
	... 23 more
```

**Comment by mcmonkey4eva** [comment]
Connected to in-progress #1788

**Comment by mcmonkey4eva** [comment]
Is this still an issue on latest dev builds http://ci.citizensnpcs.co/job/Denizen_Developmental/  ?
We've pushed quite a few 1.13 fixes recently
