### ISSUE TITLE
Invisible Command Problem

### ISSUE THREAD

**Issue by Elxafil** [DenizenScript/Denizen-For-Bukkit#1811]
So it's pretty simple and straightforward, when using the invisible command on an entity I get this error:
`[00:25:49 INFO]: +- Executing dCommand: INVISIBLE/p@Elxafil ---------+
[00:25:49 INFO]: +> Executing 'INVISIBLE': state='true'  target='e@cd8d7530-f1a5-495c-baf6-dc2b419cc0f8'
[00:25:49 INFO]:  ERROR! Woah!! An exception has been called with this command (while executing it)!
[00:25:49 INFO]:  ERROR! Internal exception was thrown!
[00:25:49 WARN]: java.lang.NullPointerException
[00:25:49 WARN]:        at org.bukkit.potion.PotionEffect.apply(PotionEffect.java:146)
[00:25:49 WARN]:        at net.aufdemrand.denizen.scripts.commands.entity.InvisibleCommand.execute(InvisibleCommand.java:100)
[00:25:49 WARN]:        at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:168)
[00:25:49 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:70)
[00:25:49 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:670)
[00:25:49 WARN]:        at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61)
[00:25:49 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.runMeNow(ScriptQueue.java:465)
[00:25:49 WARN]:        at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:516)
[00:25:49 WARN]:        at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1227)
[00:25:49 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:25:49 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:25:49 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[00:25:49 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[00:25:49 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[00:25:49 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:25:49 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:25:49 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[00:25:49 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:25:49 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:25:49 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[00:25:49 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[00:25:49 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[00:25:49 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[00:25:49 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[00:25:49 WARN]:        at java.lang.Thread.run(Thread.java:748)
[00:25:49 INFO]: +> [Denizen] (Attempted: INVISIBLE "e@cd8d7530-f1a5-495c-baf6-dc2b419cc0f8" "state:true")
[00:25:49 INFO]: +---------------------+
[00:25:49 INFO]:  Completing queue 'EXCOMMAND_ScheduleOddsIde' in 8ms.
`

**Comment by mcmonkey4eva** [comment]
What exactly where you applying the invisible command on? NPC/player/specific mob type?

**Comment by mcmonkey4eva** [comment]
My best guess offhand is that you applied to to a non-spawned, dead, or non-living entity.
A non-living entity being things like paintings, projectiles, etc. anything that's an entity (thing that moves) but is not a mob.

**Comment by Elxafil** [comment]
So would there be no way to make an item frame invisible?

**Comment by mcmonkey4eva** [comment]
Uh... removing it, given it does nothing if you can't see it as it's a visual entity?

Alternately: `hide_entity` mechanism.

**Comment by Elxafil** [comment]
Well I want to still hold an item in it but just make the frame invisible.

**Comment by mergu** [comment]
A couple alternatives are to spawn an item entity or place items on an invisible armor stand.
