### ISSUE TITLE
EventException on inventory click

### ISSUE THREAD

**Issue by SlimeDog** [DenizenScript/Denizen-For-Bukkit#1855]
```
>version
[17:05:08 INFO]: This server is running CraftBukkit version git-Spigot-e769fe4-5f5a676 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[17:05:08 INFO]: You are running the latest version
>version Citizens
[17:05:13 INFO]: Citizens version 2.0.24-SNAPSHOT (build 1595)
[17:05:13 INFO]: Website: http://www.citizensnpcs.co
[17:05:13 INFO]: Authors: aPunch and fullwall
>version denizen
[17:05:17 INFO]: Denizen version 1.0.3-SNAPSHOT (build 479-DEV)
[17:05:17 INFO]: Authors: aufdemrand, mcmonkey and Morphan1
```

The issue is:
Clicked on DeluxeMenus inventory item, which transports player (in the same world).
```
[17:01:50 ERROR]: Could not pass event InventoryClickEvent to Denizen v1.0.3-SNAPSHOT (build 479-DEV)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2127) ~[spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTTagString.b_()Ljava/lang/String;
        at net.aufdemrand.denizen.nms.impl.jnbt.CompoundTag_v1_13_R2.fromNMSTag(CompoundTag_v1_13_R2.java:105) ~[?:?]
        at net.aufdemrand.denizen.nms.impl.jnbt.CompoundTag_v1_13_R2.fromNMSTag(CompoundTag_v1_13_R2.java:113) ~[?:?]
        at net.aufdemrand.denizen.nms.impl.jnbt.CompoundTag_v1_13_R2.fromNMSTag(CompoundTag_v1_13_R2.java:93) ~[?:?]
        at net.aufdemrand.denizen.nms.helpers.ItemHelper_v1_13_R2.getNbtData(ItemHelper_v1_13_R2.java:97) ~[?:?]
        at net.aufdemrand.denizen.scripts.containers.core.ItemScriptHelper.getItemScriptContainer(ItemScriptHelper.java:180) ~[?:?]
        at net.aufdemrand.denizen.scripts.containers.core.ItemScriptHelper.isItemscript(ItemScriptHelper.java:173) ~[?:?]
        at net.aufdemrand.denizen.objects.dItem.isItemscript(dItem.java:431) ~[?:?]
        at net.aufdemrand.denizen.objects.dItem.identifySimple(dItem.java:554) ~[?:?]
        at net.aufdemrand.denizen.scripts.containers.core.BukkitWorldScriptHelper.inventoryClickEvent(BukkitWorldScriptHelper.java:288) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar-2018-12-06-1215:git-Spigot-e769fe4-5f5a676]
        ... 15 more
```

**Comment by mcmonkey4eva** [comment]
Look to be missing an NMS method.
Possibly Spigot renamed it in a recent patch...

**Comment by mcmonkey4eva** [comment]
Fixed in dev build 481
Thanks for the report!
