### ISSUE TITLE
Bug Denizen not load Error

### ISSUE THREAD

**Issue by jajamic** [DenizenScript/Denizen-For-Bukkit#1930]
The output of `/version` on my server is: The last build of Spigot
The output of `/version denizen` on my server is: Last build Denizen on Spigot
```
[23:15:58 INFO]: [Denizen] Enabling Denizen v1.0.3-SNAPSHOT (build 1655-REL)
[23:15:58 ERROR]: Error occurred while enabling Denizen v1.0.3-SNAPSHOT (build 1655-REL) (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.getMappingsVersion()Ljava/lang/String;
at net.aufdemrand.denizen.Denizen.onEnable(Denizen.java:350) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[minecraft_server.jar:git-Spigot-518206a-a5b9c7b]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [minecraft_server.jar:git-Spigot-518206a-a5b9c7b]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [minecraft_server.jar:git-Spigot-518206a-a5b9c7b]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [minecraft_server.jar:git-Spigot-518206a-a5b9c7b]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [minecraft_server.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [minecraft_server.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [minecraft_server.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [minecraft_server.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [minecraft_server.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [minecraft_server.jar:git-Spigot-518206a-a5b9c7b]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by MusicScore** [comment]
You are *not* running the latest build of Denizen.
The latest stable build is: https://ci.citizensnpcs.co/job/Denizen/lastSuccessfulBuild/
The latest dev build is: https://ci.citizensnpcs.co/job/Denizen_Developmental/lastSuccessfulBuild/

"The last build of Spigot" is not a version, but it's clear from the error that you are not on the latest 1.13.2 Spigot build. Please update your Spigot build to the latest.

**Comment by jajamic** [comment]
My last build on spigot is:

[Redacted link]

So yes it s last build? 1.13.2

**Comment by MusicScore** [comment]
Use Buildtools to make Spigot. Don't download it from other sites.

https://www.spigotmc.org/wiki/buildtools/

**Comment by mergu** [comment]
Edited post to remove potentially malicious link. You should only be using BuildTools to get Spigot. Any other site offering Spigot builds is doing so illegally and may be distributing modified, malicious, jars.

Alternatively, if you don't like running BuildTools you may consider using Paper. It's a Spigot fork and has easy-download builds readily available: https://papermc.io/
