### ISSUE TITLE
Invalid Yaml

### ISSUE THREAD

**Issue by akai7** [DenizenScript/Denizen-For-Bukkit#1955]
The output of `/version` on my server is: spigot-1.14
The output of `/version denizen` on my server is: denizen-v1_14_R1-1.0.5-SNAPSHOT.jar
[14:42:40] [Server thread/ERROR]: Could not load 'plugins\denizen-v1_14_R1-1.0.5-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.14.jar:git-Spigot-c529d43-9926d78]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:137) [spigot-1.14.jar:git-Spigot-c529d43-9926d78]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:347) [spigot-1.14.jar:git-Spigot-c529d43-9926d78]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot-1.14.jar:git-Spigot-c529d43-9926d78]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758) [spigot-1.14.jar:git-Spigot-c529d43-9926d78]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more

**Comment by mcmonkey4eva** [comment]
Where did you get the jar file you're trying to use? It's not a valid one, and it didn't come from the dev builds page: https://ci.citizensnpcs.co/job/Denizen_Developmental/

**Comment by Morphan1** [comment]
It looks like the 1.14 module. Make sure that if you're on a specific build page you download the build in the circle, as opposed to anything else.
![image](https://user-images.githubusercontent.com/4834997/57042315-50b95a80-6c32-11e9-9880-0ce057e27546.png)

**Comment by akai7** [comment]
Ooo, sorry my bad. Thanks guys
