### ISSUE TITLE
IllegalStateException: AsyncPlayerPreLoginEvent on player connect

### ISSUE THREAD

**Issue by SlimeDog** [DenizenScript/Denizen-For-Bukkit#1961]
Spigot 1.14.1 (Jenkins 2294) git-Spigot-8043ebc-dd99c5b (and previous builds)
Citizens 2.0.25-b1691
Denizen 1.0.6-b788-DEV

On player connect:
```
[07:17:30] [User Authenticator #1/INFO]: Disconnecting com.mojang.authlib.GameProfile@PLAYER_UUID_MASKED,name=PLAYER_NAME_MASKED,properties={textures=[com.mojang.authlib.properties.Property@6d4a8c51]},legacy=false] (/108.226.240.191:62953): Failed to verify username!
[07:17:30] [User Authenticator #1/WARN]: Exception verifying PLAYER_NAME_MASKED
java.lang.IllegalStateException: AsyncPlayerPreLoginEvent cannot be triggered asynchronously from primary server thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:497) ~[spigot-1.14.1.jar-2019-05-14-0633:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:266) ~[spigot-1.14.1.jar-2019-05-14-0633:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.LoginListener$2.run(LoginListener.java:216) [spigot-1.14.1.jar-2019-05-14-0633:git-Spigot-8043ebc-dd99c5b]
[07:17:30] [Server thread/INFO]: com.mojang.authlib.GameProfile@33e641c[id=3cf9b867-2577-49d1-affb-7ba8196a0d39,name= PLAYER_NAME_MASKED,properties={textures=[com.mojang.authlib.properties.Property@6d4a8c51]},legacy=false] (/108.226.240.191:62953) lost connection: Failed to verify username!
```
This issue occurs on Spigot 1.14.1 with minimal plugin subset:
```
DelayJoin 1.0-SNAPSHOT
DeluxeMenus 1.10.5
EssentialsX 2.16.1.155
EssentialsXChat 2.16.1.155
ItemJoin 5.0.4-b237
Multiverse Core-3.0.0-b761
Multiverse Inventories-3.0.0-b452
Multiverse NetherPortals-3.0.0-b749
Multiverse Portals-3.0.0-b790
PlaceholderAPI 2.10.2-b74
ProtocolLib 4.5.0-b8
Vault 1.7.2-b107
VoidGenerator 1.4.2
VoidSpawn 1.18.0
worldedit bukkit-7.0.0-b4271
worldguard legacy-7.0.0-b1880
Citizens 2.0.25-b1691
Denizen 1.0.6-b788
```
Without Denizen, there is no issue and player can connect. With same plugins on Spigot 1.13.2 final or Spigot 1.14, there is no issue and player can connect.

Denizen/config.yml (comments elided):
```
Scripts:
    Scripts location:
        Alternative folder path: 'plugins/Denizen'
        Use default script folder: true
    Queue speed: 0.5s
    World:
        Events:
            On player chats:
                Use asynchronous event: false
            On time changes:
                Frequency of check: 250t
times_changed: 1
Packets:
    Interception: true
Commands:
    Delete:
        Allow file deletion: true
    Webget:
        Allow: true
    Log:
        Allow logging: true
    Chat:
        Options:
            Multiple targets format: "%target%, %target%, %target%, and others"
            Range for bystanders: 5.0
        Formats:
            No target: "[<def[talker].name>]: <def[message]>"
            With targets to bystanders: "[<def[talker].name>] -> [<def[targets]>]: <def[message]>"
            To target: "[<def[talker].name>] -> You: <def[message]>"
            With target to bystanders: "[<def[talker].name>] -> <def[target].name>: <def[message]>"
    Filecopy:
        Allow copying files: true
    While:
        Max loops: 10000
    Restart:
        Allow server restart: false
        Allow server stop: false
    Engage:
        Timeout: 150s
    Yaml:
        Allow saving outside folder: false
Triggers:
    Proximity:
        Cooldown: 1s
        Enabled: false
        Range: 10
    Chat:
        Overhearing range: 4
        Prerequisites:
            Must be able to see NPC: true
            Must be looking in direction of NPC: true
        Use asynchronous event: true
        Cooldown: 2s
        Enabled: true
        Appears globally:
            If NPC uninteractable: true
            If triggers failed: false
            If triggers missing: true
        Formats:
            Player to NPC: "You -> <npc.name.nickname>: <text>"
            Player to NPC overheard: "<player.name> -> <npc.name.nickname>: <text>"
        Range: 3
    Click:
        Cooldown: 2s
        Enabled: true
    Damage:
        Cooldown: 0.5s
        Enabled: false
Debug:
    Allow console redirection: false
    Ex command help: true
    Override help: true
    Ex command debug: true
    Stats: false
    Show: false
    Line length: 128
    Container default: true
    Trim length limit: 1024
Traits:
    Health:
        Animated death:
            Enabled: false
        Enabled: false
        Respawn:
            Enabled: false
            Delay: 10s
Tags:
    Warning rate: 10000
    Block tags:
        Max blocks: 1000000
    Timeout: 10
    Timeout when silent: false
    Chat history:
        Max messages: 10
```

**Comment by SlimeDog** [comment]
Per the configuration above, on server start-up Denizen reports:
```
[07:17:04] [Server thread/INFO]: [Denizen] Enabling Denizen v1.0.6-SNAPSHOT (build 788-DEV)
[07:17:04] [Server thread/WARN]: [Denizen] -------------------------------------
[07:17:04] [Server thread/WARN]: [Denizen] This build of Denizen was built for a different Spigot revision! This may potentially cause issues. If you are experiencing trouble, update Denizen and Spigot both to latest builds! If this message appears with both Denizen and Spigot fully up-to-date, contact the Denizen team (via GitHub, Spigot, or Discord) to request an update be built.
[07:17:04] [Server thread/WARN]: [Denizen] -------------------------------------
[07:17:04] [Server thread/INFO]: +> [Denizen] Initializing Denizen Core v1.40-SNAPSHOT (Build 259), implementation for Bukkit version 1.0.6-SNAPSHOT (build
                   788-DEV) 
```
so the result is not a complete surprise.

**Comment by mcmonkey4eva** [comment]
That's likely a Spigot issue, refer to Paper commit here: https://github.com/PaperMC/Paper/commit/1672ac6fc11d38dc76e0c7c92ceba1cc1a170bf5

**Comment by SlimeDog** [comment]
Before I can post a ticket to Spigot, I need to understand what is the interaction that causes no issue with the exact same server setup, with Denizen not installed.

**Comment by mcmonkey4eva** [comment]
Not necessary to do.

**Comment by mcmonkey4eva** [comment]
Issue not present on 1.14.1-compatible initial Denizen build (DEV-789+)

**Comment by SlimeDog** [comment]
Ah, I misunderstood "likely a Spigot issue." :)

Confirmed fix with DEV-790. Thanks.

**Comment by mcmonkey4eva** [comment]
It _is_ an issue directly caused by Spigot (Denizen makes calls to the AsyncCatcher, but Spigot changed it so that the call will just break the server's basic functionality entirely), but it's not one worth bothering them about. Generally when paper makes a commit to fix something (as was linked) you can trust that Spigot's just gonna not bother to, or will do on their own (perhaps via speaking with Paper devs).
Easier either way to just adapt the AsyncCatcher calls in Denizen to avoid the issue.
