### ISSUE TITLE
1.14.1

### ISSUE THREAD

**Issue by FxRayHughes** [DenizenScript/Denizen-For-Bukkit#1963]
`[17:31:27] [Server thread/INFO]: com.mojang.authlib.GameProfile@7bb68e22[id=9a420e24-e32b-39ab-a6a8-c9a340d7da20,name=MoeWhite,properties={},legacy=false] (/112.96.112.212:56830) lost connection: Disconnected
[17:31:27] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to Denizen v1.0.5-SNAPSHOT (build 1674-REL)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$14(PlayerChunkMap.java:354) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:1.8.0_211]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:496) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:192) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:904) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at net.aufdemrand.denizen.objects.dEntity.isCitizensNPC(dEntity.java:99) ~[?:?]
	at net.aufdemrand.denizen.objects.dEntity.<init>(dEntity.java:377) ~[?:?]
	at net.aufdemrand.denizen.scripts.containers.core.EntityScriptHelper.onChunkUnload(EntityScriptHelper.java:84) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	... 17 more
[17:31:27] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to Denizen v1.0.5-SNAPSHOT (build 1674-REL)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$14(PlayerChunkMap.java:354) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:1.8.0_211]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:496) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:192) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:904) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at net.aufdemrand.denizen.objects.dEntity.isCitizensNPC(dEntity.java:99) ~[?:?]
	at net.aufdemrand.denizen.objects.dEntity.<init>(dEntity.java:377) ~[?:?]
	at net.aufdemrand.denizen.scripts.containers.core.EntityScriptHelper.onChunkUnload(EntityScriptHelper.java:84) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	... 17 more
[17:31:27] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to Denizen v1.0.5-SNAPSHOT (build 1674-REL)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$14(PlayerChunkMap.java:354) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:1.8.0_211]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:496) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:192) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:904) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at net.aufdemrand.denizen.objects.dEntity.isCitizensNPC(dEntity.java:99) ~[?:?]
	at net.aufdemrand.denizen.objects.dEntity.<init>(dEntity.java:377) ~[?:?]
	at net.aufdemrand.denizen.scripts.containers.core.EntityScriptHelper.onChunkUnload(EntityScriptHelper.java:84) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-02b466c]
	... 17 more`

**Comment by mergu** [comment]
I'm sorry, we do not support minecraft hacking or cracking. Your server is in offline mode. Please replicate the issue on a legitimate server
