### ISSUE TITLE
Incompatibility with HamsterAPI

### ISSUE THREAD

**Issue by Mowstyl** [DenizenScript/Denizen-For-Bukkit#2236]
The output of `/version` on my server is: git-Paper-370
The output of `/version denizen` on my server is: Denizen-1.1.4-b1707-REL
The issue is:
This plugin is not compatible with [HamsterAPI](https://www.spigotmc.org/resources/2ls-hamsterapi.78831/).
It makes HamsterAPI show this after a player joins.
[13:58:15] [Server thread/WARN]: java.lang.NoSuchFieldException: networkManager
[13:58:15] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[13:58:15] [Server thread/WARN]: 	at dev._2lstudios.hamsterapi.hamsterplayer.HamsterPlayer.<init>(HamsterPlayer.java:38)
[13:58:15] [Server thread/WARN]: 	at dev._2lstudios.hamsterapi.hamsterplayer.HamsterPlayerManager.add(HamsterPlayerManager.java:13)
[13:58:15] [Server thread/WARN]: 	at dev._2lstudios.hamsterapi.hamsterplayer.HamsterPlayerManager.get(HamsterPlayerManager.java:34)
[13:58:15] [Server thread/WARN]: 	at dev._2lstudios.hamsterapi.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:15)
[13:58:15] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor108.execute(Unknown Source)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:58:15] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerList.postChunkLoadJoin(PlayerList.java:240)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerList.lambda$null$1(PlayerList.java:187)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:373)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:142)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1353)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[13:58:15] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:58:15] [Server thread/WARN]: java.lang.NullPointerException
[13:58:15] [Server thread/WARN]: 	at dev._2lstudios.hamsterapi.utils.PacketInjector.addPlayer(PacketInjector.java:30)
[13:58:15] [Server thread/WARN]: 	at dev._2lstudios.hamsterapi.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:17)
[13:58:15] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor108.execute(Unknown Source)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:58:15] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:58:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerList.postChunkLoadJoin(PlayerList.java:240)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerList.lambda$null$1(PlayerList.java:187)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:373)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:142)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1353)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[13:58:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[13:58:15] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
I've already contacted with the authors of the plugin and they've told me that I should contact you.
Thanks in advance!

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
