### ISSUE TITLE
if <player.item_in_hand.display> == "error when barehanded"

### ISSUE THREAD

**Issue by Pyroxian** [DenizenScript/Denizen-For-Bukkit#227]
I get a huge error in the console

01:37:21 [SEVERE] Could not pass event ReplaceableTagEvent to Denizen v0.8-prere
lease
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at net.aufdemrand.denizen.tags.TagManager.tag(TagManager.java:81)
        at net.aufdemrand.denizen.tags.TagManager.fillArguments(TagManager.java:
117)
        at net.aufdemrand.denizen.scripts.commands.CommandExecuter.execute(Comma
ndExecuter.java:120)
        at net.aufdemrand.denizen.scripts.ScriptEngine.revolve(ScriptEngine.java
:43)
        at net.aufdemrand.denizen.scripts.ScriptQueue.revolve(ScriptQueue.java:2
59)
        at net.aufdemrand.denizen.scripts.ScriptQueue.start(ScriptQueue.java:240
)
        at net.aufdemrand.denizen.npc.actions.ActionHandler.doAction(ActionHandl
er.java:42)
        at net.aufdemrand.denizen.npc.dNPC.action(dNPC.java:148)
        at net.aufdemrand.denizen.scripts.triggers.core.ProximityTrigger.proximi
tyTrigger(ProximityTrigger.java:246)
        at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java
:216)
        at net.minecraft.server.v1_5_R3.Packet10Flying.handle(SourceFile:136)
        at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292
)
        at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java
:109)
        at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:3
0)
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:5
81)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:2
26)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:4
77)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java
:410)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:5
73)
Caused by: java.lang.NullPointerException
        at net.aufdemrand.denizen.tags.core.PlayerTags.playerTags(PlayerTags.jav
a:214)
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        ... 30 more

**Comment by sirbandersnatch** [comment]
@Pyroxian  @davidcernat ,
May I ask a question of you in this thread?
What is the proper syntax to detect if a Custom Item is in a player's hand?
This is what I'm trying to do.
```
if <player.item_in_hand.display["Heernack's Letter"]> {
do stuff
}
```

**Comment by mcmonkey4eva** [comment]
@sirbandersnatch Such questions are best asked either in our IRC -> http://mcmonkey.org/ircchat_denizen -> or in new issues.

And it is:

```
- if <player.item_in_hand.display||null> == "Heernack's Letter" {
  - do stuff
  }
```

**Comment by sirbandersnatch** [comment]
Thanks @mcmonkey4eva 
and duly noted.
