### ISSUE TITLE
IllegalStateException on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [DenizenScript/Denizen-For-Bukkit#2279]
Relevant versions:
```
>version
[10:14:04] [Server thread/INFO]: This server is running CraftBukkit version 3180-Spigot-38e6c03-ca0fe5b (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[10:14:04] [Server thread/INFO]: You are running the latest version
>version citizens
[10:14:34] [Server thread/INFO]: Citizens version 2.0.28-SNAPSHOT (build 2350)
[10:14:34] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[10:14:34] [Server thread/INFO]: Author: fullwall
>version denizen
[10:15:30] [Server thread/INFO]: Denizen version 1.2.1-SNAPSHOT (build 5662-DEV)
[10:15:30] [Server thread/INFO]: Author: The DenizenScript Team
```
(PluginManager is not installed.)

Updated Citizens from 2.0.28-b2349 to 2.0.28-b2350. Otherwise, the server was unchanged.

After server start-up, these events occur repeatedly -- several per second. This issue does not occur with previous versions of Citizens.

Reverting to Citizens 2.0.28-b2349 resolves the issue.
```
[10:45:17] [Server thread/WARN]: [Denizen] Task #93 for Denizen v1.2.1-SNAPSHOT (build 5662-DEV) generated an exception
java.lang.IllegalStateException: no implementation set
        at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:79) ~[?:?]
        at net.citizensnpcs.api.CitizensAPI.getNPCRegistry(CitizensAPI.java:111) ~[?:?]
        at com.denizenscript.denizen.scripts.triggers.core.ProximityTrigger.lambda$onEnable$0(ProximityTrigger.java:101) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by mcmonkey4eva** [comment]
Citizens issues get reported to Citizens.

Denizen issues get reported on Discord @ https://discord.gg/Q6pZGSR

That is a Citizens issue, post it on the Citizens issues page with full server logs (not snippets).
