### ISSUE TITLE
Could not pass event PlayerMoveEvent to Denizen v1.2.8-SNAPSHOT (build 1795-REL)

### ISSUE THREAD

**Issue by Loran-frontend** [DenizenScript/Denizen-For-Bukkit#2647]
Could not pass event PlayerMoveEvent to Denizen v1.2.8-SNAPSHOT (build 1795-REL)
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "com.denizenscript.denizen.objects.LocationTag.getWorld()" is null
        at com.denizenscript.denizen.objects.EllipsoidTag.contains(EllipsoidTag.java:200) ~[Denizen-1.2.8-b1795-REL.jar:?]
        at com.denizenscript.denizen.objects.EllipsoidTag.doesContainLocation(EllipsoidTag.java:638) ~[Denizen-1.2.8-b1795-REL.jar:?]
        at com.denizenscript.denizen.events.entity.AreaEnterExitScriptEvent.processSingle(AreaEnterExitScriptEvent.java:229) ~[Denizen-1.2.8-b1795-REL.jar:?]
        at com.denizenscript.denizen.events.entity.AreaEnterExitScriptEvent.processNewPosition(AreaEnterExitScriptEvent.java:286) ~[Denizen-1.2.8-b1795-REL.jar:?]
        at com.denizenscript.denizen.events.entity.AreaEnterExitScriptEvent$SpigotListeners.onMove(AreaEnterExitScriptEvent.java:312) ~[Denizen-1.2.8-b1795-REL.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor115.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:git-Purpur-1990]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.jar:git-Purpur-1990]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.jar:git-Purpur-1990]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1672) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.jar:git-Purpur-1990]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Hydroxycobalamin** [comment]
Support is on Discord https://discord.gg/Q6pZGSR.
