### ISSUE TITLE
Error in the console

### ISSUE THREAD

**Issue by Lordome3** [DenizenScript/Denizen-For-Bukkit#2668]
Please help me, I have uploaded the Denizen plugin to my server and this error is coming out
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/denizen ' in plugin Denizen v1.3.1-SNAPSHOT (build 7081-DEV)

at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.command.Command.tabComplete(Command.java:93) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:232) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.v1_21_R1.CraftServer.tabCompleteCommand(CraftServer.java:2209) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at org.bukkit.craftbukkit.v1_21_R1.CraftServer.tabComplete(CraftServer.java:2181) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at org.bukkit.craftbukkit.v1_21_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:60) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.2.9.jar:4226-Spigot-146439e-2889b3a]

at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:542) ~[spigot-1.21-R0.1-SNAPSHOT.jar:?]

at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:524) ~[spigot-1.21-R0.1-SNAPSHOT.jar:?]

at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:735) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.network.protocol.game.PacketPlayInTabComplete.a(SourceFile:37) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.network.protocol.game.PacketPlayInTabComplete.a(SourceFile:9) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]

at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]

Caused by: java.lang.NullPointerException: Cannot invoke "com.denizenscript.denizen.utilities.command.manager.CommandManager.onTabComplete(org.bukkit.command.CommandSender, org.bukkit.command.Command, String, String[])" because "this.commandManager" is null

at com.denizenscript.denizen.Denizen.onTabComplete(Denizen.java:594) ~[?:?]

at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]

... 26 more
How to solve this problem?

**Comment by mcmonkey4eva** [comment]
support is on discord https://discord.gg/Q6pZGSR

**Comment by dandud100** [comment]
The last build for 1.21.1 was https://ci.citizensnpcs.co/job/Denizen_Developmental/7081/
