### ISSUE TITLE
Denizen build 1560 breaks depenizen?

### ISSUE THREAD

**Issue by michalet** [DenizenScript/Denizen-For-Bukkit#943]
Although the error is fired by depenizen, I believe it's caused by denizen, as it started occuring after I updated Denizen.

```
18:17:41 [SEVERE] Error occurred while enabling Depenizen v0.2.1 (build 232) (Is it up to date?)
18:17:42 java.lang.NoSuchMethodError: net.aufdemrand.denizen.Denizen.getPropertyParser()Lnet/aufdemrand/denizen/objects/properties/PropertyParser;
18:17:42 	at net.gnomeffinway.depenizen.support.SupportManager.<init>(SupportManager.java:26) ~[?:?]
18:17:42 	at net.gnomeffinway.depenizen.support.Supported.setup(Supported.java:23) ~[?:?]
18:17:42 	at net.gnomeffinway.depenizen.Depenizen.checkPlugins(Depenizen.java:53) ~[?:?]
18:17:42 	at net.gnomeffinway.depenizen.Depenizen.onEnable(Depenizen.java:22) ~[?:?]
18:17:42 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.jar:git-Spigot-c46583f-e6f9fd4]
18:17:42 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-c46583f-e6f9fd4]
18:17:42 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-c46583f-e6f9fd4]
18:17:42 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) [spigot-1.8.jar:git-Spigot-c46583f-e6f9fd4]
18:17:42 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) [spigot-1.8.jar:git-Spigot-c46583f-e6f9fd4]
18:17:42 	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8.jar:git-Spigot-c46583f-e6f9fd4]
18:17:42 	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8.jar:git-Spigot-c46583f-e6f9fd4]
18:17:42 	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8.jar:git-Spigot-c46583f-e6f9fd4]
18:17:42 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8.jar:git-Spigot-c46583f-e6f9fd4]
18:17:42 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot-1.8.jar:git-Spigot-c46583f-e6f9fd4]
18:17:42 	at java.lang.Thread.run(Unknown Source) [?:1.7.0_05]
```

**Comment by mcmonkey4eva** [comment]
Yeah we're waiting on @Morphan1 to update Depenizen to match the recent Denizen update.

**Comment by Morphan1** [comment]
Latest Depenizen fixes this
